// packages/vue/src/Autocomplete.vue
<template>
  <ytz-autocomplete
    :open="open || undefined"
    :multiple="multiple || undefined"
    :loading="loading || undefined"
    :filter="filter !== undefined ? filter : undefined"
    :class="$attrs.class"
    @change="handleChange"
    @input-change="handleInputChange"
    @open="handleOpen"
    @close="handleClose"
    @clear="handleClear"
    v-bind="$attrs"
  >
    <slot />
  </ytz-autocomplete>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-autocomplete Web Component.
 * Provides v-model for two-way binding with full TypeScript support.
 *
 * @module @grimoire/yetzirah-vue/Autocomplete
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selectedValue">
 *     <input slot="input" placeholder="Search..." />
 *     <ytz-option value="apple">Apple</ytz-option>
 *     <ytz-option value="banana">Banana</ytz-option>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selectedValues" multiple>
 *     <input slot="input" placeholder="Select multiple..." />
 *     <ytz-option value="a">Option A</ytz-option>
 *     <ytz-option value="b">Option B</ytz-option>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <Autocomplete v-model="value" :open="isOpen" :loading="isLoading" :filter="false">
 *     <input slot="input" placeholder="Custom filtering..." />
 *     <ytz-option v-for="item in items" :key="item.id" :value="item.id">
 *       {{ item.label }}
 *     </ytz-option>
 *   </Autocomplete>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the Autocomplete component
 */
interface Props {
  /**
   * The selected value (two-way bindable via v-model)
   * String for single-select, array of strings for multi-select
   */
  modelValue?: string | string[]

  /**
   * Whether the dropdown is open
   */
  open?: boolean

  /**
   * Enable multi-select mode
   */
  multiple?: boolean

  /**
   * Show loading state
   */
  loading?: boolean

  /**
   * Enable automatic filtering of options (default: true)
   */
  filter?: boolean
}

/**
 * Emits for the Autocomplete component
 */
interface Emits {
  /**
   * Emitted when selected value changes
   * @param value The new selected value(s)
   */
  (e: 'update:modelValue', value: string | string[]): void

  /**
   * Native change event with detail.value and detail.option
   * @param event The change event
   */
  (e: 'change', event: CustomEvent): void

  /**
   * Emitted when input value changes (typing)
   * @param event Event with detail.value (input text)
   */
  (e: 'input-change', event: CustomEvent): void

  /**
   * Emitted when dropdown opens
   * @param event The open event
   */
  (e: 'open', event: Event): void

  /**
   * Emitted when dropdown closes
   * @param event The close event
   */
  (e: 'close', event: Event): void

  /**
   * Emitted when selection is cleared
   * @param event The clear event
   */
  (e: 'clear', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const value = defineModel<string | string[]>('modelValue', { default: '' })

/**
 * Handle change events from the underlying web component
 */
function handleChange(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && detail.value !== undefined) {
    value.value = detail.value
  }
  emit('change', event as CustomEvent)
}

/**
 * Handle input-change events (typing in the input)
 */
function handleInputChange(event: Event) {
  emit('input-change', event as CustomEvent)
}

/**
 * Handle open event
 */
function handleOpen(event: Event) {
  emit('open', event)
}

/**
 * Handle close event
 */
function handleClose(event: Event) {
  emit('close', event)
}

/**
 * Handle clear event
 */
function handleClear(event: Event) {
  value.value = ''
  emit('clear', event)
}
</script>

// packages/svelte/src/Autocomplete.svelte
<script lang="ts">
	import '@grimoire/yetzirah-core'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-autocomplete Web Component.
	 * Provides text input with filterable dropdown selection.
	 * Supports single and multi-select modes with async loading.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Autocomplete bind:value={selected}>
	 *   <input slot="input" placeholder="Search..." />
	 *   <AutocompleteOption value="apple">Apple</AutocompleteOption>
	 *   <AutocompleteOption value="banana">Banana</AutocompleteOption>
	 * </Autocomplete>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Autocomplete multiple bind:value={selectedItems}>
	 *   <input slot="input" placeholder="Select multiple..." />
	 *   <AutocompleteOption value="a">Option A</AutocompleteOption>
	 *   <AutocompleteOption value="b">Option B</AutocompleteOption>
	 * </Autocomplete>
	 * ```
	 */

	let element: HTMLElement & {
		open?: boolean
		multiple?: boolean
		loading?: boolean
		filter?: boolean
		value?: string | string[]
		inputValue?: string
		show?: () => void
		hide?: () => void
		toggle?: () => void
		clear?: () => void
		setOptions?: (options: Array<{ value: string; label: string; disabled?: boolean }>) => void
	}

	/** Controlled value state (string for single-select, array for multi-select) */
	export let value: string | string[] = ''

	/** Input value (text currently in the input field) */
	export let inputValue: string = ''

	/** Whether the dropdown is open */
	export let open: boolean = false

	/** Enable multi-select mode */
	export let multiple: boolean = false

	/** Show loading state */
	export let loading: boolean = false

	/** Enable client-side filtering */
	export let filter: boolean = true

	/**
	 * Handle change events from the web component
	 * @private
	 */
	function handleChange(event: CustomEvent<{ value: string | string[]; option: HTMLElement }>) {
		if (event.detail) {
			value = event.detail.value
		}
	}

	/**
	 * Handle input-change events from the web component
	 * @private
	 */
	function handleInputChange(event: CustomEvent<{ value: string }>) {
		if (event.detail) {
			inputValue = event.detail.value
		}
	}

	/**
	 * Handle open events from the web component
	 * @private
	 */
	function handleOpen() {
		open = true
	}

	/**
	 * Handle close events from the web component
	 * @private
	 */
	function handleClose() {
		open = false
	}

	/**
	 * Handle clear events from the web component
	 * @private
	 */
	function handleClear() {
		value = multiple ? [] : ''
		inputValue = ''
	}

	/**
	 * Sync value to web component
	 * @private
	 */
	$: if (element && element.value !== value) {
		element.value = value
	}

	/**
	 * Sync inputValue to web component
	 * @private
	 */
	$: if (element && element.inputValue !== inputValue) {
		element.inputValue = inputValue
	}

	/**
	 * Sync open state to web component
	 * @private
	 */
	$: if (element) {
		element.open = open
	}

	/**
	 * Sync multiple state to web component
	 * @private
	 */
	$: if (element) {
		element.multiple = multiple
	}

	/**
	 * Sync loading state to web component
	 * @private
	 */
	$: if (element) {
		element.loading = loading
	}

	/**
	 * Sync filter state to web component
	 * @private
	 */
	$: if (element) {
		element.filter = filter
	}

	onMount(() => {
		if (element) {
			element.addEventListener('change', handleChange)
			element.addEventListener('input-change', handleInputChange)
			element.addEventListener('open', handleOpen)
			element.addEventListener('close', handleClose)
			element.addEventListener('clear', handleClear)

			return () => {
				element.removeEventListener('change', handleChange)
				element.removeEventListener('input-change', handleInputChange)
				element.removeEventListener('open', handleOpen)
				element.removeEventListener('close', handleClose)
				element.removeEventListener('clear', handleClear)
			}
		}
	})

	// Expose methods for programmatic control
	export function show() {
		element?.show?.()
	}

	export function hide() {
		element?.hide?.()
	}

	export function toggle() {
		element?.toggle?.()
	}

	export function clear() {
		element?.clear?.()
	}

	export function setOptions(options: Array<{ value: string; label: string; disabled?: boolean }>) {
		element?.setOptions?.(options)
	}
</script>

<ytz-autocomplete
	bind:this={element}
	class={$$restProps.class || ''}
	{open}
	{multiple}
	{loading}
	filter={filter ? 'true' : 'false'}
	on:change
	on:input-change
	on:open
	on:close
	on:clear
	{...$$restProps}
>
	<slot />
</ytz-autocomplete>

<style>
	:global(ytz-autocomplete) {
		display: inline-block;
		position: relative;
		width: 100%;
	}

	:global(ytz-autocomplete [role='listbox']) {
		position: fixed;
		background: white;
		border: 1px solid var(--color-border, #ccc);
		border-radius: 4px;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
		max-height: 300px;
		overflow-y: auto;
		z-index: 1000;
	}

	:global(ytz-autocomplete input) {
		width: 100%;
		padding: 8px 12px;
		border: 1px solid var(--color-border, #ccc);
		border-radius: 4px;
		font-size: 14px;
		line-height: 1.5;
	}

	:global(ytz-autocomplete input:focus) {
		outline: none;
		border-color: var(--color-primary, #1976d2);
		box-shadow: 0 0 0 2px rgba(25, 118, 210, 0.1);
	}
</style>
