// packages/vue/src/Badge.vue
<template>
  <ytz-badge
    :value="value ?? undefined"
    :max="max"
    :position="position"
    :hidden="isHidden || undefined"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-badge>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-badge Web Component.
 * Provides notification badge with dot, count, and hidden modes.
 *
 * @module @grimoire-intel/yetzirah-vue/Badge
 *
 * @example
 * <template>
 *   <!-- Dot badge -->
 *   <Badge>
 *     <IconButton icon="notifications" />
 *   </Badge>
 *
 *   <!-- Count badge -->
 *   <Badge :value="5">
 *     <IconButton icon="mail" />
 *   </Badge>
 *
 *   <!-- Max cap badge -->
 *   <Badge :value="99" :max="50">
 *     <IconButton icon="inbox" />
 *   </Badge>
 * </template>
 */

import '@grimoire-intel/yetzirah'
import { computed } from 'vue'

/**
 * Badge position options
 */
export type BadgePosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left'

/**
 * Props for the Badge component
 */
interface Props {
  /**
   * Badge value. Null for dot mode, number/string for count mode.
   * Value of 0 or "0" hides the badge.
   */
  value?: string | number | null

  /**
   * Maximum displayed value. Shows "max+" when exceeded.
   */
  max?: number

  /**
   * Badge position relative to slotted content
   * @default 'top-right'
   */
  position?: BadgePosition

  /**
   * Force hide the badge
   */
  hidden?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  position: 'top-right'
})

/**
 * Whether the badge should be hidden
 */
const isHidden = computed(() => {
  if (props.hidden) return true
  if (props.value === 0 || props.value === '0') return true
  return false
})

/**
 * Current badge mode
 */
const mode = computed(() => {
  if (isHidden.value) return 'hidden'
  if (props.value === null || props.value === undefined) return 'dot'
  return 'count'
})

defineExpose({ mode, isHidden })
</script>

// packages/svelte/src/Badge.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'

	/**
	 * Svelte wrapper for ytz-badge Web Component.
	 * Provides notification badge with dot, count, and hidden modes.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <!-- Dot badge -->
	 * <Badge>
	 *   <IconButton icon="notifications" />
	 * </Badge>
	 *
	 * <!-- Count badge -->
	 * <Badge value={5}>
	 *   <IconButton icon="mail" />
	 * </Badge>
	 *
	 * <!-- Max cap badge -->
	 * <Badge value={99} max={50}>
	 *   <IconButton icon="inbox" />
	 * </Badge>
	 * ```
	 */

	type BadgePosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left'

	let element: HTMLElement

	/** Badge value. Null for dot mode, number/string for count mode. */
	export let value: string | number | null = null

	/** Maximum displayed value. Shows "max+" when exceeded. */
	export let max: number | undefined = undefined

	/** Badge position relative to slotted content */
	export let position: BadgePosition = 'top-right'

	/** Force hide the badge */
	export let hidden = false

	/** Whether the badge should be hidden */
	$: isHidden = hidden || value === 0 || value === '0'

	/** Current badge mode */
	$: mode = isHidden ? 'hidden' : (value === null || value === undefined) ? 'dot' : 'count'
</script>

<ytz-badge
	bind:this={element}
	class={$$restProps.class || ''}
	value={value ?? undefined}
	{max}
	{position}
	hidden={isHidden || undefined}
	{...$$restProps}
>
	<slot />
</ytz-badge>
