// packages/react/src/button.js
/**
 * React wrapper for ytz-button Web Component.
 * Provides polymorphic button/anchor based on props.
 *
 * @module @grimoire/yetzirah-react/button
 */

import '@grimoire/yetzirah-core'
import { forwardRef, useRef, useImperativeHandle } from 'react'

/**
 * Button component - renders as <a> when href provided, <button> otherwise.
 *
 * @param {Object} props - Component props
 * @param {string} [props.href] - If provided, renders as anchor
 * @param {Function} [props.onClick] - Click handler
 * @param {string} [props.className] - CSS classes (appended to defaults)
 * @param {boolean} [props.disabled] - Disable button (button only)
 * @param {string} [props.type] - Button type: 'button' | 'submit' | 'reset'
 * @param {React.ReactNode} props.children - Button content
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Button href="/dashboard" className="ph3 pv2 br2 white bg-blue">
 *   Dashboard
 * </Button>
 *
 * @example
 * <Button onClick={handleSubmit} className="ph3 pv2 br2 white bg-blue">
 *   Submit
 * </Button>
 */
export const Button = forwardRef(function Button(
  { href, onClick, className, disabled, type, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  return (
    <ytz-button
      ref={innerRef}
      href={href}
      class={className}
      disabled={disabled || undefined}
      type={type}
      onClick={onClick}
      {...props}
    >
      {children}
    </ytz-button>
  )
})

// packages/svelte/src/Button.svelte
<!--
  Svelte wrapper for ytz-button Web Component.
  Polymorphic button/anchor that renders <a> when href provided, <button> otherwise.

  @module @grimoire/yetzirah-svelte/Button
-->
<script>
  import '@grimoire/yetzirah-core'

  /**
   * Button component - polymorphic button/anchor.
   * Renders as <a> when href is provided, <button> otherwise.
   *
   * @slot default - Button text or content
   *
   * @example
   * <Button on:click={handleSubmit}>Submit</Button>
   *
   * @example
   * <Button href="/dashboard">Go to Dashboard</Button>
   *
   * @example
   * <Button disabled>Disabled Button</Button>
   *
   * @example
   * <Button type="submit">Submit Form</Button>
   */

  /** Optional href for navigation (makes it an anchor) */
  export let href = undefined

  /** Disable button (only applies when href is not set) */
  export let disabled = false

  /** Button type attribute (only applies when href is not set) */
  export let type = 'button'
</script>

<ytz-button
  href={href || undefined}
  {disabled}
  {type}
  class={$$props.class}
  {...$$restProps}
  on:click
>
  <slot />
</ytz-button>

<style>
  /* Component inherits styles from web component */
</style>
