// packages/react/src/chip.js
/**
 * React wrapper for ytz-chip Web Component.
 * Provides deletable tag/label with keyboard support.
 *
 * @module @grimoire-intel/yetzirah-react/chip
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useImperativeHandle, useEffect, useCallback } from 'react'

/**
 * Chip component - deletable tag/label.
 *
 * @param {Object} props - Component props
 * @param {boolean} [props.deletable] - Show delete button
 * @param {Function} [props.onDelete] - Delete handler (receives event with detail.chip)
 * @param {boolean} [props.disabled] - Disable chip interactions
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Chip content
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Chip deletable onDelete={() => removeTag(id)}>
 *   JavaScript
 * </Chip>
 *
 * @example
 * <Chip disabled>Read-only tag</Chip>
 */
export const Chip = forwardRef(function Chip(
  { deletable, onDelete, disabled, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Handle delete events from the web component
  const handleDelete = useCallback((e) => {
    if (onDelete) {
      onDelete(e)
    }
  }, [onDelete])

  // Set up event listener for delete events
  useEffect(() => {
    const el = innerRef.current
    if (!el) return

    el.addEventListener('delete', handleDelete)
    return () => el.removeEventListener('delete', handleDelete)
  }, [handleDelete])

  return (
    <ytz-chip
      ref={innerRef}
      class={className}
      deletable={deletable || undefined}
      disabled={disabled || undefined}
      {...props}
    >
      {children}
    </ytz-chip>
  )
})

// packages/svelte/src/Chip.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-chip Web Component.
	 * Provides a deletable tag/label with keyboard support.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Chip deletable on:delete={removeTag}>JavaScript</Chip>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Chip disabled>Read-only tag</Chip>
	 * ```
	 */

	let element: HTMLElement & { deletable?: boolean; disabled?: boolean }

	/** Show delete button */
	export let deletable = false

	/** Disable chip interactions */
	export let disabled = false

	/**
	 * Handle delete events from the web component
	 * @private
	 */
	function handleDelete(event: CustomEvent<{ chip: HTMLElement }>) {
		// Event is dispatched by the web component
		// Just forward it through Svelte's event system
	}

	/**
	 * Sync deletable state to web component
	 * @private
	 */
	$: if (element) {
		element.deletable = deletable
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	onMount(() => {
		if (element) {
			element.addEventListener('delete', handleDelete)

			return () => {
				element.removeEventListener('delete', handleDelete)
			}
		}
	})
</script>

<ytz-chip
	bind:this={element}
	class={$$restProps.class || ''}
	{deletable}
	{disabled}
	on:delete
	{...$$restProps}
>
	<slot />
</ytz-chip>

<style>
	:global(ytz-chip) {
		display: inline-flex;
		align-items: center;
	}
</style>
