// packages/vue/src/Dialog.vue
<template>
  <ytz-dialog
    :open="open || undefined"
    :static="staticDialog || undefined"
    :class="$attrs.class"
    @close="handleClose"
    v-bind="$attrs"
  >
    <slot />
  </ytz-dialog>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-dialog Web Component.
 * Provides v-model:open for two-way binding with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/Dialog
 *
 * @example
 * <template>
 *   <Dialog v-model:open="showDialog">
 *     <h2>Dialog Title</h2>
 *     <p>Content goes here.</p>
 *     <button @click="showDialog = false">Close</button>
 *   </Dialog>
 * </template>
 *
 * @example
 * <template>
 *   <Dialog :open="true" static>
 *     <h2>Static Dialog</h2>
 *     <p>Cannot be dismissed by clicking backdrop.</p>
 *   </Dialog>
 * </template>
 */

import '@grimoire-intel/yetzirah'
import { computed } from 'vue'

/**
 * Props for the Dialog component
 */
interface Props {
  /**
   * The open state (two-way bindable via v-model:open)
   */
  open?: boolean

  /**
   * Prevent backdrop dismiss when true
   */
  static?: boolean
}

/**
 * Emits for the Dialog component
 */
interface Emits {
  /**
   * Emitted when dialog state changes
   * @param value The new open state
   */
  (e: 'update:open', value: boolean): void

  /**
   * Native close event
   * @param event The close event
   */
  (e: 'close', event: Event): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const open = defineModel<boolean>('open', { default: false })

// Rename 'static' prop to avoid conflicts with reserved keyword
const staticDialog = computed(() => props.static)

/**
 * Handle close events from the underlying web component
 */
function handleClose(event: Event) {
  // Dialog emits close event when closing, set open to false
  open.value = false
  emit('close', event)
}
</script>

// packages/svelte/src/Dialog.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-dialog Web Component.
	 * Provides Svelte-idiomatic two-way binding with bind:open.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Dialog bind:open={isOpen}>
	 *   <h2>Dialog Title</h2>
	 *   <p>Content goes here.</p>
	 *   <button on:click={() => isOpen = false}>Close</button>
	 * </Dialog>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Dialog bind:open={isOpen} isStatic>
	 *   <h2>Static Dialog</h2>
	 *   <p>Cannot be dismissed by clicking backdrop</p>
	 * </Dialog>
	 * ```
	 */

	let element: HTMLElement & { open?: boolean }

	/** Controlled open state (two-way bindable via bind:open) */
	export let open = false

	/** Prevent backdrop dismiss */
	export let isStatic: boolean = false

	/**
	 * Handle close events from the web component
	 * @private
	 */
	function handleClose(event: CustomEvent) {
		open = false
	}

	/**
	 * Sync open state to web component
	 * @private
	 */
	$: if (element) {
		element.open = open
	}

	onMount(() => {
		if (element) {
			element.addEventListener('close', handleClose)

			return () => {
				element.removeEventListener('close', handleClose)
			}
		}
	})
</script>

<ytz-dialog
	bind:this={element}
	class={$$restProps.class || ''}
	static={isStatic || undefined}
	on:close
	{...$$restProps}
>
	<slot />
</ytz-dialog>

<style>
	:global(ytz-dialog) {
		display: none;
	}

	:global(ytz-dialog:not([hidden])) {
		display: flex;
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		align-items: center;
		justify-content: center;
		background: rgba(0, 0, 0, 0.5);
		z-index: 1000;
	}
</style>
