// packages/react/src/disclosure.js
/**
 * React wrapper for ytz-disclosure Web Component.
 * Provides controlled/uncontrolled open state management.
 *
 * @module @grimoire-intel/yetzirah-react/disclosure
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useEffect, useImperativeHandle } from 'react'

/**
 * Disclosure component - expandable content with toggle trigger.
 *
 * @param {Object} props - Component props
 * @param {boolean} [props.open] - Controlled open state
 * @param {boolean} [props.defaultOpen] - Initial open state (uncontrolled)
 * @param {Function} [props.onToggle] - Callback when open state changes
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Trigger button and content elements
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Disclosure open={open} onToggle={setOpen}>
 *   <button>Toggle</button>
 *   <div>Content</div>
 * </Disclosure>
 */
export const Disclosure = forwardRef(function Disclosure(
  { open, defaultOpen, onToggle, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Sync controlled open prop to attribute
  useEffect(() => {
    const el = innerRef.current
    if (!el || open === undefined) return

    if (open) {
      el.setAttribute('open', '')
    } else {
      el.removeAttribute('open')
    }
  }, [open])

  // Handle toggle events
  useEffect(() => {
    const el = innerRef.current
    if (!el || !onToggle) return

    const handleToggle = (e) => onToggle(e.detail.open)

    el.addEventListener('toggle', handleToggle)
    return () => el.removeEventListener('toggle', handleToggle)
  }, [onToggle])

  return (
    <ytz-disclosure
      ref={innerRef}
      class={className}
      open={defaultOpen || undefined}
      {...props}
    >
      {children}
    </ytz-disclosure>
  )
})

// packages/svelte/src/Disclosure.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-disclosure Web Component.
	 * Provides Svelte-idiomatic two-way binding with bind:open.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Disclosure bind:open={isExpanded}>
	 *   <button>Show Details</button>
	 *   <div>Hidden content...</div>
	 * </Disclosure>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Disclosure open>
	 *   <button>Hide Details</button>
	 *   <div>Initially visible content...</div>
	 * </Disclosure>
	 * ```
	 */

	let element: HTMLElement & { open?: boolean }

	/** Controlled open state */
	export let open = false

	/**
	 * Handle toggle events from the web component
	 * @private
	 */
	function handleToggle(event: CustomEvent<{ open: boolean }>) {
		if (event.detail) {
			open = event.detail.open
		}
	}

	/**
	 * Sync open state to web component
	 * @private
	 */
	$: if (element) {
		element.open = open
	}

	onMount(() => {
		if (element) {
			element.addEventListener('toggle', handleToggle)

			return () => {
				element.removeEventListener('toggle', handleToggle)
			}
		}
	})
</script>

<ytz-disclosure
	bind:this={element}
	class={$$restProps.class || ''}
	on:toggle
	{...$$restProps}
>
	<slot />
</ytz-disclosure>

<style>
	:global(ytz-disclosure) {
		display: block;
	}
</style>
