// packages/react/src/drawer.js
/**
 * React wrapper for ytz-drawer Web Component.
 * Provides slide-in panel with focus trap, scroll lock, and escape-to-close.
 *
 * @module @grimoire-intel/yetzirah-react/drawer
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useEffect, useImperativeHandle } from 'react'

/**
 * Drawer component - slide-in panel from screen edge.
 *
 * @param {Object} props - Component props
 * @param {boolean} [props.open] - Controls drawer visibility
 * @param {Function} [props.onClose] - Callback when drawer closes
 * @param {'left'|'right'|'top'|'bottom'} [props.anchor='left'] - Edge to anchor to
 * @param {boolean} [props.static] - Prevents backdrop click close
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Drawer content
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Drawer open={isOpen} onClose={() => setOpen(false)} anchor="left">
 *   <nav className="w5 h-100 bg-white pa4">
 *     <a href="/home">Home</a>
 *   </nav>
 * </Drawer>
 */
export const Drawer = forwardRef(function Drawer(
  { open, onClose, anchor = 'left', static: isStatic, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Sync open prop to attribute
  useEffect(() => {
    const el = innerRef.current
    if (!el) return

    if (open) {
      el.setAttribute('open', '')
    } else {
      el.removeAttribute('open')
    }
  }, [open])

  // Handle close events
  useEffect(() => {
    const el = innerRef.current
    if (!el || !onClose) return

    el.addEventListener('close', onClose)
    return () => el.removeEventListener('close', onClose)
  }, [onClose])

  return (
    <ytz-drawer
      ref={innerRef}
      class={className}
      anchor={anchor}
      static={isStatic || undefined}
      {...props}
    >
      {children}
    </ytz-drawer>
  )
})

// packages/svelte/src/Drawer.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-drawer Web Component.
	 * Provides Svelte-idiomatic two-way binding with bind:open.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Drawer bind:open={isOpen} anchor="left">
	 *   <nav>
	 *     <a href="/home">Home</a>
	 *   </nav>
	 * </Drawer>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Drawer bind:open={menuOpen} anchor="right" static>
	 *   <div>Sidebar content</div>
	 * </Drawer>
	 * ```
	 */

	let element: HTMLElement & { open?: boolean; anchor?: string }

	/** Controlled open state */
	export let open = false

	/** Anchor position: 'left', 'right', 'top', or 'bottom' */
	export let anchor: 'left' | 'right' | 'top' | 'bottom' = 'left'

	/**
	 * Handle close events from the web component
	 * @private
	 */
	function handleClose(event: CustomEvent) {
		open = false
	}

	/**
	 * Sync open state to web component
	 * @private
	 */
	$: if (element) {
		element.open = open
	}

	/**
	 * Sync anchor state to web component
	 * @private
	 */
	$: if (element) {
		element.anchor = anchor
	}

	onMount(() => {
		if (element) {
			element.addEventListener('close', handleClose)

			return () => {
				element.removeEventListener('close', handleClose)
			}
		}
	})
</script>

<ytz-drawer
	bind:this={element}
	class={$$restProps.class || ''}
	{anchor}
	on:close
	{...$$restProps}
>
	<slot />
</ytz-drawer>

<style>
	:global(ytz-drawer) {
		display: block;
	}
</style>
