// packages/vue/src/ListboxOption.vue
<template>
  <ytz-option
    :value="value"
    :disabled="disabled || undefined"
    :selected="selected || undefined"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-option>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-option Web Component (used within Listbox).
 * Represents a selectable option in a listbox.
 *
 * @module @grimoire/yetzirah-vue/ListboxOption
 *
 * @example
 * <template>
 *   <Listbox v-model="selected">
 *     <ListboxOption value="1">Option 1</ListboxOption>
 *     <ListboxOption value="2">Option 2</ListboxOption>
 *     <ListboxOption value="3" disabled>Option 3 (disabled)</ListboxOption>
 *   </Listbox>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the ListboxOption component
 */
interface Props {
  /**
   * The value of this option
   */
  value?: string

  /**
   * Whether the option is disabled
   */
  disabled?: boolean

  /**
   * Whether the option is selected (managed by parent listbox)
   */
  selected?: boolean
}

defineProps<Props>()
</script>

// packages/svelte/src/ListboxOption.svelte
<script lang="ts">
	import '@grimoire/yetzirah-core'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-option Web Component.
	 * Individual option in a listbox.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <ListboxOption value="apple">Apple</ListboxOption>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <ListboxOption value="banana" disabled>Banana (out of stock)</ListboxOption>
	 * ```
	 */

	let element: HTMLElement & {
		disabled?: boolean
		selected?: boolean
		value?: string | null
	}

	/** Option value */
	export let value: string = ''

	/** Disabled state */
	export let disabled: boolean = false

	/** Selected state (managed by parent listbox) */
	export let selected: boolean = false

	/**
	 * Sync value to web component
	 * @private
	 */
	$: if (element && value) {
		element.value = value
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	/**
	 * Sync selected state to web component
	 * @private
	 */
	$: if (element) {
		element.selected = selected
	}

	onMount(() => {
		// Component handles its own click events internally
	})
</script>

<ytz-option
	bind:this={element}
	class={$$restProps.class || ''}
	{value}
	{disabled}
	{selected}
	{...$$restProps}
>
	<slot />
</ytz-option>

<style>
	:global(ytz-option) {
		display: block;
		padding: 8px 12px;
		cursor: pointer;
		user-select: none;
	}

	:global(ytz-option:hover:not([disabled])) {
		background-color: var(--color-background-hover, #f5f5f5);
	}

	:global(ytz-option:focus) {
		outline: none;
		background-color: var(--color-background-focus, #e3f2fd);
	}

	:global(ytz-option[selected]) {
		background-color: var(--color-background-selected, #e3f2fd);
		font-weight: 500;
	}

	:global(ytz-option[disabled]) {
		opacity: 0.5;
		cursor: not-allowed;
	}
</style>
