// packages/vue/src/Menu.vue
<template>
  <ytz-menu
    :open="open || undefined"
    :placement="placement"
    @open="handleOpen"
    @close="handleClose"
    v-bind="$attrs"
    :class="$attrs.class"
  >
    <slot name="trigger" slot="trigger" />
    <slot />
  </ytz-menu>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-menu Web Component.
 * Dropdown menu with keyboard navigation, positioned relative to trigger.
 *
 * @module @grimoire-intel/yetzirah-vue/Menu
 *
 * @example
 * <template>
 *   <Menu>
 *     <template #trigger>
 *       <button>Open Menu</button>
 *     </template>
 *     <MenuItem>Edit</MenuItem>
 *     <MenuItem>Delete</MenuItem>
 *   </Menu>
 * </template>
 *
 * @example
 * <template>
 *   <Menu :open="isOpen" placement="bottom-start" @close="handleClose">
 *     <template #trigger>
 *       <button>Actions</button>
 *     </template>
 *     <MenuItem value="edit">Edit</MenuItem>
 *     <MenuItem disabled>Archive</MenuItem>
 *   </Menu>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the Menu component
 */
interface Props {
  /**
   * Controlled open state
   */
  open?: boolean

  /**
   * Menu placement relative to trigger
   * @default 'bottom-start'
   */
  placement?: string
}

/**
 * Emits for the Menu component
 */
interface Emits {
  /**
   * Emitted when menu opens
   * @param event The open event
   */
  (e: 'open', event: CustomEvent): void

  /**
   * Emitted when menu closes
   * @param event The close event
   */
  (e: 'close', event: CustomEvent): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

/**
 * Handle open events from the underlying web component
 */
function handleOpen(event: Event) {
  emit('open', event as CustomEvent)
}

/**
 * Handle close events from the underlying web component
 */
function handleClose(event: Event) {
  emit('close', event as CustomEvent)
}
</script>

// packages/svelte/src/Menu.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-menu Web Component.
	 * Dropdown menu with keyboard navigation, positioned relative to trigger.
	 * Provides Svelte-idiomatic two-way binding with bind:open.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Menu bind:open={isOpen}>
	 *   <button slot="trigger">Open Menu</button>
	 *   <MenuItem>Edit</MenuItem>
	 *   <MenuItem>Delete</MenuItem>
	 * </Menu>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Menu placement="bottom-start">
	 *   <button slot="trigger">Actions</button>
	 *   <MenuItem value="edit">Edit</MenuItem>
	 *   <MenuItem disabled>Archive</MenuItem>
	 * </Menu>
	 * ```
	 */

	let element: HTMLElement & { open?: boolean; placement?: string }

	/** Controlled open state */
	export let open = false

	/** Menu placement relative to trigger */
	export let placement = 'bottom-start'

	/**
	 * Handle open events from the web component
	 * @private
	 */
	function handleOpen(event: CustomEvent) {
		open = true
	}

	/**
	 * Handle close events from the web component
	 * @private
	 */
	function handleClose(event: CustomEvent) {
		open = false
	}

	/**
	 * Sync open state to web component
	 * @private
	 */
	$: if (element) {
		element.open = open
	}

	/**
	 * Sync placement to web component
	 * @private
	 */
	$: if (element) {
		element.placement = placement
	}

	onMount(() => {
		if (element) {
			element.addEventListener('open', handleOpen)
			element.addEventListener('close', handleClose)

			return () => {
				element.removeEventListener('open', handleOpen)
				element.removeEventListener('close', handleClose)
			}
		}
	})
</script>

<ytz-menu
	bind:this={element}
	class={$$restProps.class || ''}
	placement={placement}
	on:open
	on:close
	{...$$restProps}
>
	<slot name="trigger" slot="trigger" />
	<slot />
</ytz-menu>

<style>
	:global(ytz-menu) {
		display: inline-block;
		position: relative;
	}
</style>
