// packages/vue/src/Progress.vue
<template>
  <ytz-progress
    :value="value ?? undefined"
    :linear="linear || undefined"
    :size="size"
    :label="label"
    :class="$attrs.class"
    v-bind="$attrs"
  />
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-progress Web Component.
 * Provides progress indicator with circular and linear modes.
 *
 * @module @grimoire-intel/yetzirah-vue/Progress
 *
 * @example
 * <template>
 *   <!-- Indeterminate spinner -->
 *   <Progress />
 *
 *   <!-- Determinate progress -->
 *   <Progress :value="75" />
 *
 *   <!-- Linear progress bar -->
 *   <Progress :value="50" linear />
 * </template>
 */

import '@grimoire-intel/yetzirah'
import { computed } from 'vue'

/**
 * Progress size options
 */
export type ProgressSize = 'small' | 'medium' | 'large'

/**
 * Props for the Progress component
 */
interface Props {
  /**
   * Progress value 0-100, null/undefined for indeterminate
   */
  value?: number | null

  /**
   * Use linear bar instead of circular spinner
   */
  linear?: boolean

  /**
   * Size variant
   * @default 'medium'
   */
  size?: ProgressSize

  /**
   * Accessible label for screen readers
   */
  label?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 'medium'
})

/**
 * Whether the progress is in indeterminate mode
 */
const indeterminate = computed(() => props.value === null || props.value === undefined)

defineExpose({ indeterminate })
</script>

// packages/svelte/src/Progress.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'

	/**
	 * Svelte wrapper for ytz-progress Web Component.
	 * Provides progress indicator with circular and linear modes.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <!-- Indeterminate spinner -->
	 * <Progress />
	 *
	 * <!-- Determinate progress -->
	 * <Progress value={75} />
	 *
	 * <!-- Linear progress bar -->
	 * <Progress value={50} linear />
	 * ```
	 */

	type ProgressSize = 'small' | 'medium' | 'large'

	let element: HTMLElement

	/** Progress value 0-100, null/undefined for indeterminate */
	export let value: number | null = null

	/** Use linear bar instead of circular spinner */
	export let linear = false

	/** Size variant */
	export let size: ProgressSize = 'medium'

	/** Accessible label for screen readers */
	export let label: string | undefined = undefined

	/** Whether the progress is in indeterminate mode */
	$: indeterminate = value === null || value === undefined
</script>

<ytz-progress
	bind:this={element}
	class={$$restProps.class || ''}
	value={value ?? undefined}
	linear={linear || undefined}
	{size}
	{label}
	{...$$restProps}
/>
