// packages/react/src/progress.js
/**
 * React wrapper for ytz-progress Web Component.
 * Provides circular spinner and linear progress bar variants.
 *
 * @module @grimoire-intel/yetzirah-react/progress
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useImperativeHandle, useEffect } from 'react'

/**
 * Progress component - spinner or progress bar.
 *
 * @param {Object} props - Component props
 * @param {number|null} [props.value] - Progress 0-100. Null/undefined for indeterminate
 * @param {boolean} [props.linear] - If true, renders as progress bar
 * @param {string} [props.size='medium'] - Size: 'small', 'medium', 'large'
 * @param {string} [props.label] - Accessible label
 * @param {string} [props.className] - CSS classes
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * // Indeterminate spinner
 * <Progress />
 *
 * @example
 * // Determinate progress bar
 * <Progress linear value={75} />
 */
export const Progress = forwardRef(function Progress(
  { value, linear, size, label, className, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Sync value prop - null/undefined = indeterminate
  useEffect(() => {
    const el = innerRef.current
    if (!el) return

    if (value === null || value === undefined) {
      el.removeAttribute('value')
    } else {
      el.setAttribute('value', String(value))
    }
  }, [value])

  return (
    <ytz-progress
      ref={innerRef}
      class={className}
      value={value ?? undefined}
      linear={linear || undefined}
      size={size}
      label={label}
      {...props}
    />
  )
})

/**
 * Spinner component - alias for indeterminate circular progress.
 *
 * @param {Object} props - Same props as Progress (except linear)
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Spinner size="small" />
 */
export const Spinner = forwardRef(function Spinner(props, ref) {
  return <Progress {...props} ref={ref} linear={false} />
})

/**
 * CircularProgress component - explicit circular variant.
 *
 * @param {Object} props - Same props as Progress (except linear)
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <CircularProgress value={75} />
 */
export const CircularProgress = forwardRef(function CircularProgress(props, ref) {
  return <Progress {...props} ref={ref} linear={false} />
})

/**
 * LinearProgress component - progress bar variant.
 *
 * @param {Object} props - Same props as Progress (linear is forced true)
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <LinearProgress value={50} />
 */
export const LinearProgress = forwardRef(function LinearProgress(props, ref) {
  return <Progress {...props} ref={ref} linear />
})

// packages/svelte/src/Progress.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'

	/**
	 * Svelte wrapper for ytz-progress Web Component.
	 * Provides progress indicator with circular and linear modes.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <!-- Indeterminate spinner -->
	 * <Progress />
	 *
	 * <!-- Determinate progress -->
	 * <Progress value={75} />
	 *
	 * <!-- Linear progress bar -->
	 * <Progress value={50} linear />
	 * ```
	 */

	type ProgressSize = 'small' | 'medium' | 'large'

	let element: HTMLElement

	/** Progress value 0-100, null/undefined for indeterminate */
	export let value: number | null = null

	/** Use linear bar instead of circular spinner */
	export let linear = false

	/** Size variant */
	export let size: ProgressSize = 'medium'

	/** Accessible label for screen readers */
	export let label: string | undefined = undefined

	/** Whether the progress is in indeterminate mode */
	$: indeterminate = value === null || value === undefined
</script>

<ytz-progress
	bind:this={element}
	class={$$restProps.class || ''}
	value={value ?? undefined}
	linear={linear || undefined}
	{size}
	{label}
	{...$$restProps}
/>
