// packages/vue/src/SelectOption.vue
<template>
  <ytz-option
    :value="value"
    :selected="selected ? '' : undefined"
    :disabled="disabled ? '' : undefined"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-option>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-option Web Component (used with Select).
 * Provides type-safe props for option elements.
 *
 * @module @grimoire/yetzirah-vue/SelectOption
 *
 * @example
 * <template>
 *   <Select v-model="selected">
 *     <SelectOption value="red">Red</SelectOption>
 *     <SelectOption value="green">Green</SelectOption>
 *     <SelectOption value="blue" disabled>Blue (unavailable)</SelectOption>
 *   </Select>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the SelectOption component
 */
interface Props {
  /**
   * The value of this option (used for selection)
   */
  value?: string

  /**
   * Whether this option is currently selected
   */
  selected?: boolean

  /**
   * Whether this option is disabled
   */
  disabled?: boolean
}

defineProps<Props>()
</script>

// packages/svelte/src/SelectOption.svelte
<script lang="ts">
	import '@grimoire/yetzirah-core'

	/**
	 * Svelte wrapper for ytz-option Web Component (used with Select).
	 * Represents a selectable option within a Select component.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <SelectOption value="1">Option 1</SelectOption>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <SelectOption value="premium" disabled>Premium (Coming Soon)</SelectOption>
	 * ```
	 */

	let element: HTMLElement & {
		disabled?: boolean
		selected?: boolean
	}

	/** The option value */
	export let value: string | undefined = undefined

	/** Disabled state */
	export let disabled = false

	/** Selected state */
	export let selected = false

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	/**
	 * Sync selected state to web component
	 * @private
	 */
	$: if (element) {
		element.selected = selected
	}
</script>

<ytz-option
	bind:this={element}
	class={$$restProps.class || ''}
	{value}
	{disabled}
	{selected}
	on:option-click
	{...$$restProps}
>
	<slot />
</ytz-option>

<style>
	:global(ytz-option) {
		display: block;
	}
</style>
