// packages/angular/src/lib/select-option.component.ts
import {
  Component,
  Input,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-option Web Component (used within ytz-select).
 * Represents an individual option in the select dropdown.
 *
 * @example
 * <ytz-select>
 *   <ytz-option value="apple">Apple</ytz-option>
 *   <ytz-option value="banana" [disabled]="true">Banana (Out of stock)</ytz-option>
 *   <ytz-option value="cherry" [selected]="true">Cherry</ytz-option>
 * </ytz-select>
 */
@Component({
  selector: 'ytz-option',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class SelectOptionComponent {
  /**
   * The value of this option
   */
  @Input() value: string = '';

  /**
   * Whether this option is disabled
   */
  @Input() disabled: boolean = false;

  /**
   * Whether this option is selected
   */
  @Input() selected: boolean = false;
}

// packages/svelte/src/SelectOption.svelte
<script lang="ts">
	import '@grimoire/yetzirah-core'

	/**
	 * Svelte wrapper for ytz-option Web Component (used with Select).
	 * Represents a selectable option within a Select component.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <SelectOption value="1">Option 1</SelectOption>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <SelectOption value="premium" disabled>Premium (Coming Soon)</SelectOption>
	 * ```
	 */

	let element: HTMLElement & {
		disabled?: boolean
		selected?: boolean
	}

	/** The option value */
	export let value: string | undefined = undefined

	/** Disabled state */
	export let disabled = false

	/** Selected state */
	export let selected = false

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	/**
	 * Sync selected state to web component
	 * @private
	 */
	$: if (element) {
		element.selected = selected
	}
</script>

<ytz-option
	bind:this={element}
	class={$$restProps.class || ''}
	{value}
	{disabled}
	{selected}
	on:option-click
	{...$$restProps}
>
	<slot />
</ytz-option>

<style>
	:global(ytz-option) {
		display: block;
	}
</style>
