// packages/react/src/snackbar.js
/**
 * React wrapper for ytz-snackbar Web Component.
 * Provides toast notifications with auto-dismiss and positioning.
 *
 * @module @grimoire-intel/yetzirah-react/snackbar
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useEffect, useImperativeHandle } from 'react'

/**
 * Snackbar component - toast notification with auto-dismiss.
 *
 * @param {Object} props - Component props
 * @param {boolean} [props.open] - Controls snackbar visibility
 * @param {Function} [props.onDismiss] - Callback when snackbar closes
 * @param {number} [props.duration=5000] - Auto-dismiss time in ms (0 = no auto-dismiss)
 * @param {string} [props.position='bottom-center'] - Position anchor
 * @param {boolean} [props.dismissible] - Shows close button
 * @param {number} [props.maxVisible=3] - Maximum snackbars at same position
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Snackbar message content
 * @param {React.Ref} ref - Forwarded ref with show/dismiss methods
 * @returns {JSX.Element}
 *
 * @example
 * <Snackbar open={showMessage} onDismiss={() => setShowMessage(false)}>
 *   File saved successfully
 * </Snackbar>
 *
 * @example
 * const ref = useRef()
 * <Snackbar ref={ref} dismissible>Message</Snackbar>
 * <Button onClick={() => ref.current.show()}>Show</Button>
 */
export const Snackbar = forwardRef(function Snackbar(
  { open, onDismiss, duration, position, dismissible, maxVisible, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => ({
    show: (message) => innerRef.current?.show(message),
    dismiss: () => innerRef.current?.dismiss(),
    get element() { return innerRef.current }
  }))

  // Sync open prop to attribute
  useEffect(() => {
    const el = innerRef.current
    if (!el || open === undefined) return

    if (open) {
      el.setAttribute('open', '')
    } else {
      el.removeAttribute('open')
    }
  }, [open])

  // Handle dismiss events
  useEffect(() => {
    const el = innerRef.current
    if (!el || !onDismiss) return

    el.addEventListener('dismiss', onDismiss)
    return () => el.removeEventListener('dismiss', onDismiss)
  }, [onDismiss])

  return (
    <ytz-snackbar
      ref={innerRef}
      class={className}
      duration={duration}
      position={position}
      dismissible={dismissible || undefined}
      max-visible={maxVisible}
      {...props}
    >
      {children}
    </ytz-snackbar>
  )
})

// packages/svelte/src/Snackbar.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-snackbar Web Component.
	 * Provides Svelte-idiomatic two-way binding with bind:open.
	 *
	 * @component
	 */

	type SnackbarPosition = 'top-left' | 'top-center' | 'top-right' | 'bottom-left' | 'bottom-center' | 'bottom-right'

	let element: HTMLElement

	/** Controlled open state (two-way bindable via bind:open) */
	export let open = false

	/** Auto-dismiss duration in milliseconds */
	export let duration = 5000

	/** Snackbar position on screen */
	export let position: SnackbarPosition = 'bottom-center'

	/** Show close button */
	export let dismissible = false

	/** Maximum number of visible stacked snackbars */
	export let maxVisible = 3

	/** Programmatically show the snackbar */
	export function show(message: string | undefined = undefined) {
		if (element && (element as any).show) {
			(element as any).show(message)
		}
		open = true
	}

	/** Programmatically dismiss the snackbar */
	export function dismiss() {
		if (element && (element as any).dismiss) {
			(element as any).dismiss()
		}
		open = false
	}

	function handleDismiss(event: Event) {
		open = false
	}

	$: if (element) {
		(element as any).open = open
	}

	onMount(() => {
		if (element) {
			element.addEventListener('dismiss', handleDismiss)

			return () => {
				element.removeEventListener('dismiss', handleDismiss)
			}
		}
	})
</script>

<ytz-snackbar
	bind:this={element}
	class={$$restProps.class || ''}
	{position}
	{duration}
	dismissible={dismissible || undefined}
	max-visible={maxVisible}
	on:dismiss
	{...$$restProps}
>
	<slot />
</ytz-snackbar>
