// packages/vue/src/TabPanel.vue
<template>
  <ytz-tabpanel
    :id="id"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-tabpanel>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-tabpanel Web Component.
 * Represents a content panel controlled by a Tab.
 *
 * @module @grimoire/yetzirah-vue/TabPanel
 *
 * @example
 * <template>
 *   <Tabs v-model="selectedTab">
 *     <Tab panel="dashboard">Dashboard</Tab>
 *     <Tab panel="reports">Reports</Tab>
 *     <TabPanel id="dashboard">Dashboard content here</TabPanel>
 *     <TabPanel id="reports">Reports content here</TabPanel>
 *   </Tabs>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the TabPanel component
 */
interface Props {
  /**
   * The panel ID matching a Tab's panel prop (required)
   */
  id: string
}

defineProps<Props>()
</script>

// packages/svelte/src/TabPanel.svelte
<script lang="ts">
	import '@grimoire/yetzirah-core'

	/**
	 * Svelte wrapper for ytz-tabpanel Web Component.
	 * Contains the content for a tab.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <TabPanel id="settings">Your settings content here</TabPanel>
	 * ```
	 */

	/** Panel ID matching a Tab's panel prop */
	export let id = ''
</script>

<ytz-tabpanel {id} class={$$restProps.class || ''} {...$$restProps}>
	<slot />
</ytz-tabpanel>

<style>
	:global(ytz-tabpanel) {
		display: block;
	}
</style>
