// packages/vue/src/Tabs.vue
<template>
  <ytz-tabs
    :value="value"
    :orientation="orientation"
    :class="$attrs.class"
    @change="handleChange"
    v-bind="$attrs"
  >
    <slot />
  </ytz-tabs>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-tabs Web Component.
 * Provides v-model for two-way binding of selected tab with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/Tabs
 *
 * @example
 * <template>
 *   <Tabs v-model="selectedTab">
 *     <Tab panel="account">Account</Tab>
 *     <Tab panel="settings">Settings</Tab>
 *     <TabPanel id="account">Account content</TabPanel>
 *     <TabPanel id="settings">Settings content</TabPanel>
 *   </Tabs>
 * </template>
 *
 * @example
 * <template>
 *   <Tabs v-model="activeTab" orientation="vertical">
 *     <Tab panel="profile">Profile</Tab>
 *     <Tab panel="privacy">Privacy</Tab>
 *     <TabPanel id="profile">Profile settings</TabPanel>
 *     <TabPanel id="privacy">Privacy settings</TabPanel>
 *   </Tabs>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the Tabs component
 */
interface Props {
  /**
   * The selected tab panel ID (two-way bindable via v-model)
   */
  modelValue?: string

  /**
   * Tab orientation
   * @default 'horizontal'
   */
  orientation?: 'horizontal' | 'vertical'
}

/**
 * Emits for the Tabs component
 */
interface Emits {
  /**
   * Emitted when selected tab changes
   * @param value The new selected panel ID
   */
  (e: 'update:modelValue', value: string): void

  /**
   * Native change event with detail.value
   * @param event The change event
   */
  (e: 'change', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const value = defineModel<string>('modelValue', { default: '' })

/**
 * Handle change events from the underlying web component
 */
function handleChange(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && typeof detail.value === 'string') {
    value.value = detail.value
  }
  emit('change', event)
}
</script>

// packages/svelte/src/Tabs.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-tabs Web Component.
	 * Provides Svelte-idiomatic two-way binding with bind:value.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Tabs bind:value={selectedTab}>
	 *   <Tab panel="tab1">Account</Tab>
	 *   <Tab panel="tab2">Settings</Tab>
	 *   <TabPanel id="tab1">Account content</TabPanel>
	 *   <TabPanel id="tab2">Settings content</TabPanel>
	 * </Tabs>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Tabs bind:value={selectedTab} orientation="vertical">
	 *   <Tab panel="home">Home</Tab>
	 *   <Tab panel="profile">Profile</Tab>
	 *   <TabPanel id="home">Home content</TabPanel>
	 *   <TabPanel id="profile">Profile content</TabPanel>
	 * </Tabs>
	 * ```
	 */

	let element: HTMLElement & { value?: string; orientation?: string }

	/** Controlled selected tab panel ID */
	export let value = ''

	/** Tab orientation */
	export let orientation: 'horizontal' | 'vertical' = 'horizontal'

	/**
	 * Handle change events from the web component
	 * @private
	 */
	function handleChange(event: CustomEvent<{ value: string }>) {
		if (event.detail) {
			value = event.detail.value
		}
	}

	/**
	 * Sync value state to web component
	 * @private
	 */
	$: if (element) {
		element.value = value
	}

	/**
	 * Sync orientation state to web component
	 * @private
	 */
	$: if (element) {
		element.orientation = orientation
	}

	onMount(() => {
		if (element) {
			element.addEventListener('change', handleChange)

			return () => {
				element.removeEventListener('change', handleChange)
			}
		}
	})
</script>

<ytz-tabs
	bind:this={element}
	class={$$restProps.class || ''}
	{orientation}
	on:change
	{...$$restProps}
>
	<slot />
</ytz-tabs>

<style>
	:global(ytz-tabs) {
		display: block;
	}
</style>
