// packages/vue/src/Tooltip.vue
<template>
  <ytz-tooltip
    :placement="placement"
    :delay="delay"
    :offset="offset"
    :class="$attrs.class"
    v-bind="$attrs"
    @show="handleShow"
    @hide="handleHide"
  >
    <slot />
    <template v-if="content || $slots.content">
      <span v-if="content" slot="content" :class="contentClass">{{ content }}</span>
      <slot v-else name="content" />
    </template>
  </ytz-tooltip>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-tooltip Web Component.
 * Provides positioned hint text on hover/focus with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/Tooltip
 *
 * @example
 * <template>
 *   <Tooltip content="Helpful hint" placement="top">
 *     <button>Hover me</button>
 *   </Tooltip>
 * </template>
 *
 * @example
 * <template>
 *   <Tooltip placement="bottom" :delay="200">
 *     <button>Hover me</button>
 *     <template #content>
 *       <strong>Rich content</strong> tooltip
 *     </template>
 *   </Tooltip>
 * </template>
 *
 * @example
 * <template>
 *   <Tooltip
 *     content="Tracked tooltip"
 *     @show="onTooltipShow"
 *     @hide="onTooltipHide"
 *   >
 *     <button>Hover me</button>
 *   </Tooltip>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the Tooltip component
 */
interface Props {
  /**
   * Tooltip content as text (for simple tooltips)
   */
  content?: string

  /**
   * Tooltip position relative to trigger
   */
  placement?: 'top' | 'bottom' | 'left' | 'right'

  /**
   * Show delay in milliseconds
   */
  delay?: number

  /**
   * Gap between trigger and tooltip
   */
  offset?: number

  /**
   * CSS classes for tooltip content (when using content prop)
   */
  contentClass?: string
}

/**
 * Emits for the Tooltip component
 */
interface Emits {
  /**
   * Emitted when tooltip shows
   * @param event The show event
   */
  (e: 'show', event: Event): void

  /**
   * Emitted when tooltip hides
   * @param event The hide event
   */
  (e: 'hide', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

/**
 * Handle show events from the underlying web component
 */
function handleShow(event: Event) {
  emit('show', event)
}

/**
 * Handle hide events from the underlying web component
 */
function handleHide(event: Event) {
  emit('hide', event)
}
</script>

// packages/svelte/src/Tooltip.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'

	/**
	 * Svelte wrapper for ytz-tooltip Web Component.
	 * Shows positioned hint text on hover/focus with configurable delay and placement.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Tooltip>
	 *   <button>Hover me</button>
	 *   <span slot="content">Tooltip text</span>
	 * </Tooltip>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Tooltip placement="bottom" delay={200}>
	 *   <button>Hover me</button>
	 *   <span slot="content">Bottom tooltip</span>
	 * </Tooltip>
	 * ```
	 */

	let element: HTMLElement & {
		placement?: 'top' | 'bottom' | 'left' | 'right'
		delay?: number
		offset?: number
		show?: () => void
		hide?: () => void
	}

	/** Tooltip placement relative to trigger */
	export let placement: 'top' | 'bottom' | 'left' | 'right' = 'top'

	/** Delay before showing tooltip on hover (in milliseconds) */
	export let delay = 0

	/** Distance from trigger element (in pixels) */
	export let offset = 8

	/**
	 * Sync placement to web component
	 * @private
	 */
	$: if (element) {
		element.placement = placement
	}

	/**
	 * Sync delay to web component
	 * @private
	 */
	$: if (element) {
		element.delay = delay
	}

	/**
	 * Sync offset to web component
	 * @private
	 */
	$: if (element) {
		element.offset = offset
	}

	/**
	 * Public API: Show the tooltip programmatically
	 */
	export function show() {
		element?.show?.()
	}

	/**
	 * Public API: Hide the tooltip programmatically
	 */
	export function hide() {
		element?.hide?.()
	}
</script>

<ytz-tooltip
	bind:this={element}
	class={$$restProps.class || ''}
	{placement}
	{delay}
	{offset}
	on:show
	on:hide
	{...$$restProps}
>
	<slot />
	<slot name="content" slot="content" />
</ytz-tooltip>

<style>
	:global(ytz-tooltip) {
		display: inline-block;
	}
</style>
