// packages/svelte/src/Badge.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'

	/**
	 * Svelte wrapper for ytz-badge Web Component.
	 * Provides notification badge with dot, count, and hidden modes.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <!-- Dot badge -->
	 * <Badge>
	 *   <IconButton icon="notifications" />
	 * </Badge>
	 *
	 * <!-- Count badge -->
	 * <Badge value={5}>
	 *   <IconButton icon="mail" />
	 * </Badge>
	 *
	 * <!-- Max cap badge -->
	 * <Badge value={99} max={50}>
	 *   <IconButton icon="inbox" />
	 * </Badge>
	 * ```
	 */

	type BadgePosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left'

	let element: HTMLElement

	/** Badge value. Null for dot mode, number/string for count mode. */
	export let value: string | number | null = null

	/** Maximum displayed value. Shows "max+" when exceeded. */
	export let max: number | undefined = undefined

	/** Badge position relative to slotted content */
	export let position: BadgePosition = 'top-right'

	/** Force hide the badge */
	export let hidden = false

	/** Whether the badge should be hidden */
	$: isHidden = hidden || value === 0 || value === '0'

	/** Current badge mode */
	$: mode = isHidden ? 'hidden' : (value === null || value === undefined) ? 'dot' : 'count'
</script>

<ytz-badge
	bind:this={element}
	class={$$restProps.class || ''}
	value={value ?? undefined}
	{max}
	{position}
	hidden={isHidden || undefined}
	{...$$restProps}
>
	<slot />
</ytz-badge>

// packages/react/src/badge.js
/**
 * React wrapper for ytz-badge Web Component.
 * Provides notification badge with count or dot indicator.
 *
 * @module @grimoire-intel/yetzirah-react/badge
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useImperativeHandle } from 'react'

/**
 * Badge component - notification indicator.
 *
 * @param {Object} props - Component props
 * @param {string|number} [props.badgeContent] - Badge value. Omit for dot mode
 * @param {number} [props.max] - Cap displayed value, shows "max+"
 * @param {boolean} [props.invisible] - Hides the badge
 * @param {string} [props.position='top-right'] - Badge position
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Anchored content
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * // Count badge
 * <Badge badgeContent={5} max={99}>
 *   <button>Notifications</button>
 * </Badge>
 *
 * @example
 * // Dot badge (no content)
 * <Badge>
 *   <span>New</span>
 * </Badge>
 */
export const Badge = forwardRef(function Badge(
  { badgeContent, max, invisible, position, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  return (
    <ytz-badge
      ref={innerRef}
      value={badgeContent}
      max={max}
      position={position}
      hidden={invisible || undefined}
      class={className}
      {...props}
    >
      {children}
    </ytz-badge>
  )
})
