// packages/vue/src/DataGrid.vue
<template>
  <ytz-datagrid
    :class="$attrs.class"
    :row-height="rowHeight"
    @sort="handleSort"
    @rowselect="handleRowClick"
    v-bind="$attrs"
  >
    <ytz-datagrid-column
      v-for="(col, index) in columns"
      :key="col.key || index"
      :field="col.key"
      :header="col.header"
      :width="col.width"
      :sortable="col.sortable"
    />
  </ytz-datagrid>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-datagrid Web Component.
 * Provides virtual scrolling, sorting, and row selection with full TypeScript support.
 *
 * @module @grimoire/yetzirah-vue/DataGrid
 *
 * @example
 * <template>
 *   <DataGrid
 *     :data="rows"
 *     :columns="[
 *       { key: 'name', header: 'Name', sortable: true },
 *       { key: 'email', header: 'Email' },
 *       { key: 'age', header: 'Age', width: '100px' }
 *     ]"
 *     @sort="onSort"
 *     @rowclick="onRowClick"
 *   />
 * </template>
 *
 * @example
 * <template>
 *   <DataGrid
 *     :data="users"
 *     :columns="cols"
 *     :row-height="40"
 *     :virtual-scroll="true"
 *   />
 * </template>
 */

import { ref, watch, nextTick } from 'vue'
import '@grimoire/yetzirah-core'

/**
 * Column definition for DataGrid
 */
export interface DataGridColumn {
  /**
   * Data field name
   */
  key: string

  /**
   * Column header text
   */
  header: string

  /**
   * Column width (CSS value)
   */
  width?: string

  /**
   * Enable sorting for this column
   */
  sortable?: boolean
}

/**
 * Props for the DataGrid component
 */
interface Props {
  /**
   * Row data array
   */
  data?: Array<Record<string, any>>

  /**
   * Column definitions
   */
  columns?: DataGridColumn[]

  /**
   * Row height in pixels
   */
  rowHeight?: number

  /**
   * Enable virtual scrolling
   */
  virtualScroll?: boolean
}

/**
 * Emits for the DataGrid component
 */
interface Emits {
  /**
   * Emitted when a column is sorted
   * @param detail Object with column and direction properties
   */
  (e: 'sort', detail: { column: string; direction: 'asc' | 'desc' }): void

  /**
   * Emitted when a row is clicked
   * @param detail Object with row data
   */
  (e: 'rowclick', detail: { row: Record<string, any> }): void
}

const props = withDefaults(defineProps<Props>(), {
  data: () => [],
  columns: () => [],
  rowHeight: 40,
  virtualScroll: true
})

const emit = defineEmits<Emits>()

const gridRef = ref<any>(null)

/**
 * Watch for data changes and update the grid
 */
watch(
  () => props.data,
  (newData) => {
    if (gridRef.value && Array.isArray(newData)) {
      nextTick(() => {
        gridRef.value.data = newData
      })
    }
  },
  { deep: true, immediate: true }
)

/**
 * Handle sort events from the underlying web component
 */
function handleSort(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && detail.field) {
    emit('sort', {
      column: detail.field,
      direction: detail.direction || 'asc'
    })
  }
}

/**
 * Handle row click events from the underlying web component
 */
function handleRowClick(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && detail.row) {
    emit('rowclick', {
      row: detail.row
    })
  }
}
</script>

<style scoped>
/* Styles are handled by the ytz-datagrid web component */
</style>

// packages/react/src/datagrid.js
/**
 * React wrapper for ytz-datagrid Web Component.
 * Provides data grid with virtual scrolling, sorting, and filtering.
 *
 * @module @grimoire/yetzirah-react/datagrid
 */

import '@grimoire/yetzirah-core'
import { forwardRef, useRef, useImperativeHandle, useEffect, useCallback, Children } from 'react'

/**
 * DataGridColumn component - defines a column for the DataGrid.
 *
 * @param {Object} props - Component props
 * @param {string} props.field - Data field name
 * @param {string} [props.header] - Column header (defaults to field)
 * @param {boolean} [props.sortable] - Enable sorting
 * @param {boolean} [props.filterable] - Enable filtering
 * @param {string} [props.width] - Column width (CSS value)
 * @returns {JSX.Element}
 */
export const DataGridColumn = forwardRef(function DataGridColumn(
  { field, header, sortable, filterable, width, ...props },
  ref
) {
  const innerRef = useRef(null)
  useImperativeHandle(ref, () => innerRef.current)

  return (
    <ytz-datagrid-column
      ref={innerRef}
      field={field}
      header={header}
      sortable={sortable || undefined}
      filterable={filterable || undefined}
      width={width}
      {...props}
    />
  )
})

/**
 * DataGrid component - virtualized data grid with sorting/filtering.
 *
 * @param {Object} props - Component props
 * @param {Array<Object>} [props.data] - Row data array
 * @param {Array<Object>} [props.columns] - Column definitions (alternative to children)
 * @param {number} [props.rowHeight=40] - Row height in pixels
 * @param {Function} [props.onSort] - Sort event handler
 * @param {Function} [props.onRowSelect] - Row selection handler
 * @param {Function} [props.onRowActivate] - Row activation (Enter key) handler
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} [props.children] - DataGridColumn children
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * // With column children
 * <DataGrid data={users} onRowSelect={(e) => console.log(e.detail.row)}>
 *   <DataGridColumn field="name" header="Name" sortable />
 *   <DataGridColumn field="email" header="Email" filterable />
 * </DataGrid>
 *
 * @example
 * // With columns prop
 * <DataGrid
 *   data={users}
 *   columns={[
 *     { field: 'name', header: 'Name', sortable: true },
 *     { field: 'email', header: 'Email', filterable: true }
 *   ]}
 * />
 */
export const DataGrid = forwardRef(function DataGrid(
  { data, columns, rowHeight, onSort, onRowSelect, onRowActivate, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Handle sort events
  const handleSort = useCallback((e) => {
    if (onSort) {
      onSort(e)
    }
  }, [onSort])

  // Handle row select events
  const handleRowSelect = useCallback((e) => {
    if (onRowSelect) {
      onRowSelect(e)
    }
  }, [onRowSelect])

  // Handle row activate events
  const handleRowActivate = useCallback((e) => {
    if (onRowActivate) {
      onRowActivate(e)
    }
  }, [onRowActivate])

  // Set up event listeners
  useEffect(() => {
    const el = innerRef.current
    if (!el) return

    el.addEventListener('sort', handleSort)
    el.addEventListener('rowselect', handleRowSelect)
    el.addEventListener('rowactivate', handleRowActivate)

    return () => {
      el.removeEventListener('sort', handleSort)
      el.removeEventListener('rowselect', handleRowSelect)
      el.removeEventListener('rowactivate', handleRowActivate)
    }
  }, [handleSort, handleRowSelect, handleRowActivate])

  // Sync data property
  useEffect(() => {
    const el = innerRef.current
    if (!el || data === undefined) return

    // Set data via property (not attribute)
    el.data = data
  }, [data])

  // Generate column elements from columns prop if provided
  const columnElements = columns
    ? columns.map((col, index) => (
        <ytz-datagrid-column
          key={col.field || index}
          field={col.field}
          header={col.header}
          sortable={col.sortable || undefined}
          filterable={col.filterable || undefined}
          width={col.width}
        />
      ))
    : children

  return (
    <ytz-datagrid
      ref={innerRef}
      class={className}
      row-height={rowHeight}
      {...props}
    >
      {columnElements}
    </ytz-datagrid>
  )
})
