// packages/vue/src/Listbox.vue
<template>
  <ytz-listbox
    :multiple="multiple || undefined"
    :disabled="disabled || undefined"
    :class="$attrs.class"
    @change="handleChange"
    v-bind="$attrs"
  >
    <slot />
  </ytz-listbox>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-listbox Web Component.
 * Provides v-model for two-way binding with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/Listbox
 *
 * @example
 * <template>
 *   <Listbox v-model="selectedValue">
 *     <ytz-option value="1">Option 1</ytz-option>
 *     <ytz-option value="2">Option 2</ytz-option>
 *   </Listbox>
 * </template>
 *
 * @example
 * <template>
 *   <Listbox v-model="selectedValues" multiple>
 *     <ytz-option value="a">Option A</ytz-option>
 *     <ytz-option value="b">Option B</ytz-option>
 *     <ytz-option value="c">Option C</ytz-option>
 *   </Listbox>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the Listbox component
 */
interface Props {
  /**
   * The selected value (two-way bindable via v-model)
   * Single value when multiple=false, array when multiple=true
   */
  modelValue?: string | string[]

  /**
   * Enable multi-select mode
   */
  multiple?: boolean

  /**
   * Whether the listbox is disabled
   */
  disabled?: boolean
}

/**
 * Emits for the Listbox component
 */
interface Emits {
  /**
   * Emitted when selection changes
   * @param value The new selected value(s)
   */
  (e: 'update:modelValue', value: string | string[]): void

  /**
   * Native change event with detail.value
   * @param event The change event
   */
  (e: 'change', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const value = defineModel<string | string[]>('modelValue', { default: '' })

/**
 * Handle change events from the underlying web component
 */
function handleChange(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && detail.value !== undefined) {
    value.value = detail.value
  }
  emit('change', event)
}
</script>

// packages/react/src/listbox.js
/**
 * React wrapper for ytz-listbox.
 * @module @grimoire-intel/yetzirah-react/listbox
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useImperativeHandle, useEffect } from 'react'

/**
 * Listbox component - keyboard-navigable list selection.
 *
 * @param {Object} props
 * @param {string|string[]} [props.value] - Controlled selected value(s)
 * @param {Function} [props.onChange] - Callback when selection changes
 * @param {boolean} [props.multiple=false] - Enable multi-select
 * @param {boolean} [props.disabled=false] - Disable all interaction
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Option children
 * @param {React.Ref} ref - Forwarded ref
 */
export const Listbox = forwardRef(function Listbox(
  { value, onChange, multiple, disabled, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)
  useImperativeHandle(ref, () => innerRef.current)

  useEffect(() => {
    const el = innerRef.current
    if (!el || value === undefined) return
    el.value = value
  }, [value])

  useEffect(() => {
    const el = innerRef.current
    if (!el) return
    const handleChange = (e) => onChange?.(e.detail.value)
    el.addEventListener('change', handleChange)
    return () => el.removeEventListener('change', handleChange)
  }, [onChange])

  return (
    <ytz-listbox
      ref={innerRef}
      class={className}
      multiple={multiple || undefined}
      disabled={disabled || undefined}
      {...props}
    >
      {children}
    </ytz-listbox>
  )
})
