// packages/svelte/src/Tabs.svelte
<script lang="ts">
	import '@grimoire/yetzirah-core'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-tabs Web Component.
	 * Provides Svelte-idiomatic two-way binding with bind:value.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Tabs bind:value={selectedTab}>
	 *   <Tab panel="tab1">Account</Tab>
	 *   <Tab panel="tab2">Settings</Tab>
	 *   <TabPanel id="tab1">Account content</TabPanel>
	 *   <TabPanel id="tab2">Settings content</TabPanel>
	 * </Tabs>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Tabs bind:value={selectedTab} orientation="vertical">
	 *   <Tab panel="home">Home</Tab>
	 *   <Tab panel="profile">Profile</Tab>
	 *   <TabPanel id="home">Home content</TabPanel>
	 *   <TabPanel id="profile">Profile content</TabPanel>
	 * </Tabs>
	 * ```
	 */

	let element: HTMLElement & { value?: string; orientation?: string }

	/** Controlled selected tab panel ID */
	export let value = ''

	/** Tab orientation */
	export let orientation: 'horizontal' | 'vertical' = 'horizontal'

	/**
	 * Handle change events from the web component
	 * @private
	 */
	function handleChange(event: CustomEvent<{ value: string }>) {
		if (event.detail) {
			value = event.detail.value
		}
	}

	/**
	 * Sync value state to web component
	 * @private
	 */
	$: if (element) {
		element.value = value
	}

	/**
	 * Sync orientation state to web component
	 * @private
	 */
	$: if (element) {
		element.orientation = orientation
	}

	onMount(() => {
		if (element) {
			element.addEventListener('change', handleChange)

			return () => {
				element.removeEventListener('change', handleChange)
			}
		}
	})
</script>

<ytz-tabs
	bind:this={element}
	class={$$restProps.class || ''}
	{orientation}
	on:change
	{...$$restProps}
>
	<slot />
</ytz-tabs>

<style>
	:global(ytz-tabs) {
		display: block;
	}
</style>

// packages/react/src/tabs.js
/**
 * React wrappers for ytz-tabs Web Components.
 * Provides controlled/uncontrolled tab selection.
 *
 * @module @grimoire/yetzirah-react/tabs
 */

import '@grimoire/yetzirah-core'
import { forwardRef, useRef, useEffect, useImperativeHandle } from 'react'

/**
 * Tabs container component.
 *
 * @param {Object} props
 * @param {string} [props.value] - Controlled selected panel id
 * @param {string} [props.defaultValue] - Initial selected panel id (uncontrolled)
 * @param {Function} [props.onChange] - Callback when selection changes
 * @param {'horizontal'|'vertical'} [props.orientation='horizontal'] - Tab orientation
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Tab and TabPanel elements
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Tabs value={tab} onChange={setTab}>
 *   <Tab panel="one">Tab 1</Tab>
 *   <Tab panel="two">Tab 2</Tab>
 *   <TabPanel id="one">Content 1</TabPanel>
 *   <TabPanel id="two">Content 2</TabPanel>
 * </Tabs>
 */
export const Tabs = forwardRef(function Tabs(
  { value, defaultValue, onChange, orientation, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Sync controlled value prop to attribute
  useEffect(() => {
    const el = innerRef.current
    if (!el || value === undefined) return
    el.setAttribute('value', value)
  }, [value])

  // Handle change events
  useEffect(() => {
    const el = innerRef.current
    if (!el || !onChange) return

    const handleChange = (e) => onChange(e.detail.value)

    el.addEventListener('change', handleChange)
    return () => el.removeEventListener('change', handleChange)
  }, [onChange])

  return (
    <ytz-tabs
      ref={innerRef}
      class={className}
      value={defaultValue || undefined}
      orientation={orientation}
      {...props}
    >
      {children}
    </ytz-tabs>
  )
})

/**
 * Tab button component.
 *
 * @param {Object} props
 * @param {string} props.panel - ID of the TabPanel this tab controls (required)
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Tab label
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 */
export const Tab = forwardRef(function Tab(
  { panel, className, children, ...props },
  ref
) {
  return (
    <ytz-tab ref={ref} class={className} panel={panel} {...props}>
      {children}
    </ytz-tab>
  )
})

/**
 * TabPanel content component.
 *
 * @param {Object} props
 * @param {string} props.id - Panel ID matching a Tab's panel prop (required)
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Panel content
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 */
export const TabPanel = forwardRef(function TabPanel(
  { id, className, children, ...props },
  ref
) {
  return (
    <ytz-tabpanel ref={ref} id={id} class={className} {...props}>
      {children}
    </ytz-tabpanel>
  )
})
