// packages/svelte/src/AccordionItem.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-accordion-item Web Component.
	 * Individual collapsible section within an accordion.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <AccordionItem>
	 *   <button>Section Title</button>
	 *   <div>Section content goes here</div>
	 * </AccordionItem>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <AccordionItem open>
	 *   <button>Initially Open Section</button>
	 *   <div>Content visible by default</div>
	 * </AccordionItem>
	 * ```
	 */

	let element: HTMLElement & { open?: boolean }

	/** Whether the item is expanded */
	export let open = false

	/**
	 * Handle toggle events from the web component
	 * @private
	 */
	function handleToggle(event: CustomEvent<{ open: boolean }>) {
		if (event.detail) {
			open = event.detail.open
		}
	}

	/**
	 * Sync open state to web component
	 * @private
	 */
	$: if (element) {
		element.open = open
	}

	onMount(() => {
		if (element) {
			element.addEventListener('toggle', handleToggle)

			return () => {
				element.removeEventListener('toggle', handleToggle)
			}
		}
	})
</script>

<ytz-accordion-item
	bind:this={element}
	class={$$restProps.class || ''}
	{open}
	on:toggle
	{...$$restProps}
>
	<slot />
</ytz-accordion-item>

<style>
	:global(ytz-accordion-item) {
		display: block;
		border-bottom: 1px solid var(--color-border, #e0e0e0);
	}

	:global(ytz-accordion-item button) {
		width: 100%;
		text-align: left;
		padding: 12px 16px;
		background: var(--color-background, white);
		border: none;
		cursor: pointer;
		font-size: 16px;
		font-weight: 500;
	}

	:global(ytz-accordion-item button:hover) {
		background: var(--color-background-hover, #f5f5f5);
	}

	:global(ytz-accordion-item button:focus) {
		outline: 2px solid var(--color-focus, #1976d2);
		outline-offset: -2px;
	}

	:global(ytz-accordion-item > div) {
		overflow: hidden;
		transition: height 0.2s ease;
	}

	:global(ytz-accordion-item[open] > div) {
		padding: 12px 16px;
	}
</style>

// packages/vue/src/AccordionItem.vue
<template>
  <ytz-accordion-item
    :open="open || undefined"
    :class="$attrs.class"
    @toggle="handleToggle"
    v-bind="$attrs"
  >
    <slot />
  </ytz-accordion-item>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-accordion-item Web Component.
 * Individual accordion panel with v-model:open for two-way binding.
 *
 * @module @grimoire-intel/yetzirah-vue/AccordionItem
 *
 * @example
 * <template>
 *   <AccordionItem v-model:open="isOpen">
 *     <button>Toggle Section</button>
 *     <div>Content goes here...</div>
 *   </AccordionItem>
 * </template>
 *
 * @example
 * <template>
 *   <AccordionItem :open="true">
 *     <button>Initially Open Section</button>
 *     <div>This content is visible by default</div>
 *   </AccordionItem>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the AccordionItem component
 */
interface Props {
  /**
   * The open state (two-way bindable via v-model:open)
   */
  open?: boolean
}

/**
 * Emits for the AccordionItem component
 */
interface Emits {
  /**
   * Emitted when accordion item state changes
   * @param value The new open state
   */
  (e: 'update:open', value: boolean): void

  /**
   * Native toggle event with detail.open
   * @param event The toggle event
   */
  (e: 'toggle', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const open = defineModel<boolean>('open', { default: false })

/**
 * Handle toggle events from the underlying web component
 */
function handleToggle(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && typeof detail.open === 'boolean') {
    open.value = detail.open
  }
  emit('toggle', event)
}
</script>
