// packages/angular/src/lib/autocomplete.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnDestroy,
  forwardRef
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-autocomplete Web Component.
 * Implements ControlValueAccessor for use with ngModel and reactive forms.
 * Provides text input with filterable dropdown selection.
 *
 * @example
 * // Reactive Forms
 * <ytz-autocomplete [formControl]="autocompleteControl">
 *   <input slot="input" placeholder="Search...">
 *   <ytz-option value="apple">Apple</ytz-option>
 *   <ytz-option value="banana">Banana</ytz-option>
 * </ytz-autocomplete>
 *
 * @example
 * // Template-driven Forms
 * <ytz-autocomplete [(ngModel)]="selectedValue">
 *   <input slot="input" placeholder="Search...">
 *   <ytz-option value="apple">Apple</ytz-option>
 * </ytz-autocomplete>
 *
 * @example
 * // Multi-select mode
 * <ytz-autocomplete [multiple]="true" [(ngModel)]="selectedValues">
 *   <input slot="input" placeholder="Select...">
 *   <ytz-option value="a">Option A</ytz-option>
 *   <ytz-option value="b">Option B</ytz-option>
 * </ytz-autocomplete>
 */
@Component({
  selector: 'ytz-autocomplete',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: [],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => AutocompleteComponent),
      multi: true
    }
  ]
})
export class AutocompleteComponent implements ControlValueAccessor, AfterViewInit, OnDestroy {
  /**
   * Whether the dropdown is open
   */
  @Input() open: boolean = false;

  /**
   * Enable multi-select mode
   */
  @Input() multiple: boolean = false;

  /**
   * Show loading indicator
   */
  @Input() loading: boolean = false;

  /**
   * Enable/disable filtering of options
   */
  @Input() filter: boolean = true;

  /**
   * Emitted when the selected value changes
   */
  @Output() change = new EventEmitter<CustomEvent>();

  /**
   * Emitted when the dropdown opens
   */
  @Output() openChange = new EventEmitter<CustomEvent>();

  /**
   * Emitted when the dropdown closes
   */
  @Output() closeChange = new EventEmitter<CustomEvent>();

  /**
   * Emitted when the input value changes
   */
  @Output() inputChange = new EventEmitter<CustomEvent>();

  @ViewChild('autocompleteElement', { read: ElementRef }) autocompleteElement!: ElementRef;

  private value: string | string[] = '';
  private onChange: ((value: string | string[]) => void) | null = null;
  private onTouched: (() => void) | null = null;

  private changeHandler = (e: Event) => {
    const customEvent = e as CustomEvent;
    const newValue = customEvent.detail?.value;
    this.value = newValue;
    this.change.emit(customEvent);

    if (this.onChange) {
      this.onChange(newValue);
    }
    if (this.onTouched) {
      this.onTouched();
    }
  };

  private openHandler = (e: Event) => {
    const customEvent = e as CustomEvent;
    this.open = true;
    this.openChange.emit(customEvent);
  };

  private closeHandler = (e: Event) => {
    const customEvent = e as CustomEvent;
    this.open = false;
    this.closeChange.emit(customEvent);
    if (this.onTouched) {
      this.onTouched();
    }
  };

  private inputChangeHandler = (e: Event) => {
    const customEvent = e as CustomEvent;
    this.inputChange.emit(customEvent);
  };

  ngAfterViewInit() {
    this.setupEventListeners();
  }

  ngOnDestroy() {
    this.removeEventListeners();
  }

  // ControlValueAccessor implementation
  writeValue(value: any): void {
    this.value = value ?? (this.multiple ? [] : '');
    const el = this.getNativeElement();
    if (el) {
      el.value = this.value;
    }
  }

  registerOnChange(fn: (value: string | string[]) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    // Autocomplete doesn't have a disabled state in the core component
    // This is here for ControlValueAccessor interface completeness
  }

  private setupEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.addEventListener('change', this.changeHandler);
      el.addEventListener('open', this.openHandler);
      el.addEventListener('close', this.closeHandler);
      el.addEventListener('input-change', this.inputChangeHandler);
    }
  }

  private removeEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.removeEventListener('change', this.changeHandler);
      el.removeEventListener('open', this.openHandler);
      el.removeEventListener('close', this.closeHandler);
      el.removeEventListener('input-change', this.inputChangeHandler);
    }
  }

  private getNativeElement(): (HTMLElement & { value?: string | string[] }) | null {
    // For standalone components with template, get the host element itself
    // since we're using selector: 'ytz-autocomplete'
    if (typeof window !== 'undefined') {
      return document.querySelector('ytz-autocomplete') as (HTMLElement & { value?: string | string[] }) | null;
    }
    return null;
  }
}

// packages/vue/src/Autocomplete.vue
<template>
  <ytz-autocomplete
    :open="open || undefined"
    :multiple="multiple || undefined"
    :loading="loading || undefined"
    :filter="filter !== undefined ? filter : undefined"
    :class="$attrs.class"
    @change="handleChange"
    @input-change="handleInputChange"
    @open="handleOpen"
    @close="handleClose"
    @clear="handleClear"
    v-bind="$attrs"
  >
    <slot />
  </ytz-autocomplete>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-autocomplete Web Component.
 * Provides v-model for two-way binding with full TypeScript support.
 *
 * @module @grimoire/yetzirah-vue/Autocomplete
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selectedValue">
 *     <input slot="input" placeholder="Search..." />
 *     <ytz-option value="apple">Apple</ytz-option>
 *     <ytz-option value="banana">Banana</ytz-option>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selectedValues" multiple>
 *     <input slot="input" placeholder="Select multiple..." />
 *     <ytz-option value="a">Option A</ytz-option>
 *     <ytz-option value="b">Option B</ytz-option>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <Autocomplete v-model="value" :open="isOpen" :loading="isLoading" :filter="false">
 *     <input slot="input" placeholder="Custom filtering..." />
 *     <ytz-option v-for="item in items" :key="item.id" :value="item.id">
 *       {{ item.label }}
 *     </ytz-option>
 *   </Autocomplete>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the Autocomplete component
 */
interface Props {
  /**
   * The selected value (two-way bindable via v-model)
   * String for single-select, array of strings for multi-select
   */
  modelValue?: string | string[]

  /**
   * Whether the dropdown is open
   */
  open?: boolean

  /**
   * Enable multi-select mode
   */
  multiple?: boolean

  /**
   * Show loading state
   */
  loading?: boolean

  /**
   * Enable automatic filtering of options (default: true)
   */
  filter?: boolean
}

/**
 * Emits for the Autocomplete component
 */
interface Emits {
  /**
   * Emitted when selected value changes
   * @param value The new selected value(s)
   */
  (e: 'update:modelValue', value: string | string[]): void

  /**
   * Native change event with detail.value and detail.option
   * @param event The change event
   */
  (e: 'change', event: CustomEvent): void

  /**
   * Emitted when input value changes (typing)
   * @param event Event with detail.value (input text)
   */
  (e: 'input-change', event: CustomEvent): void

  /**
   * Emitted when dropdown opens
   * @param event The open event
   */
  (e: 'open', event: Event): void

  /**
   * Emitted when dropdown closes
   * @param event The close event
   */
  (e: 'close', event: Event): void

  /**
   * Emitted when selection is cleared
   * @param event The clear event
   */
  (e: 'clear', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const value = defineModel<string | string[]>('modelValue', { default: '' })

/**
 * Handle change events from the underlying web component
 */
function handleChange(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && detail.value !== undefined) {
    value.value = detail.value
  }
  emit('change', event as CustomEvent)
}

/**
 * Handle input-change events (typing in the input)
 */
function handleInputChange(event: Event) {
  emit('input-change', event as CustomEvent)
}

/**
 * Handle open event
 */
function handleOpen(event: Event) {
  emit('open', event)
}

/**
 * Handle close event
 */
function handleClose(event: Event) {
  emit('close', event)
}

/**
 * Handle clear event
 */
function handleClear(event: Event) {
  value.value = ''
  emit('clear', event)
}
</script>
