// packages/svelte/src/AutocompleteOption.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-option Web Component.
	 * Individual option in autocomplete dropdown.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <AutocompleteOption value="apple">Apple</AutocompleteOption>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <AutocompleteOption value="banana" disabled>Banana (out of stock)</AutocompleteOption>
	 * ```
	 */

	let element: HTMLElement & {
		disabled?: boolean
		selected?: boolean
		value?: string | null
	}

	/** Option value */
	export let value: string = ''

	/** Disabled state */
	export let disabled: boolean = false

	/** Selected state (managed by parent autocomplete) */
	export let selected: boolean = false

	/**
	 * Sync value to web component
	 * @private
	 */
	$: if (element && value) {
		element.value = value
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	/**
	 * Sync selected state to web component
	 * @private
	 */
	$: if (element) {
		element.selected = selected
	}

	onMount(() => {
		// Component handles its own click events internally
	})
</script>

<ytz-option
	bind:this={element}
	class={$$restProps.class || ''}
	{value}
	{disabled}
	{selected}
	{...$$restProps}
>
	<slot />
</ytz-option>

<style>
	:global(ytz-option) {
		display: block;
		padding: 8px 12px;
		cursor: pointer;
		user-select: none;
	}

	:global(ytz-option:hover:not([disabled])) {
		background-color: var(--color-background-hover, #f5f5f5);
	}

	:global(ytz-option:focus) {
		outline: none;
		background-color: var(--color-background-focus, #e3f2fd);
	}

	:global(ytz-option[selected]) {
		background-color: var(--color-background-selected, #e3f2fd);
		font-weight: 500;
	}

	:global(ytz-option[disabled]) {
		opacity: 0.5;
		cursor: not-allowed;
	}
</style>

// packages/vue/src/AutocompleteOption.vue
<template>
  <ytz-option
    :value="value"
    :disabled="disabled || undefined"
    :selected="selected || undefined"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-option>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-option Web Component (used within Autocomplete/Listbox/Select).
 * Provides Vue-idiomatic API with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/AutocompleteOption
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selected">
 *     <input slot="input" placeholder="Search..." />
 *     <AutocompleteOption value="apple">Apple</AutocompleteOption>
 *     <AutocompleteOption value="banana">Banana</AutocompleteOption>
 *     <AutocompleteOption value="orange" disabled>Orange (out of stock)</AutocompleteOption>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <AutocompleteOption :value="item.id" :selected="item.selected">
 *     {{ item.label }}
 *   </AutocompleteOption>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the AutocompleteOption component
 */
interface Props {
  /**
   * The option value
   */
  value?: string

  /**
   * Whether the option is disabled
   */
  disabled?: boolean

  /**
   * Whether the option is selected (managed by parent Autocomplete)
   */
  selected?: boolean
}

defineProps<Props>()
</script>
