// packages/react/src/autocomplete.js
/**
 * React wrappers for ytz-autocomplete Web Components.
 * Text input with filterable dropdown selection.
 *
 * @module @grimoire-intel/yetzirah-react/autocomplete
 */

import '@grimoire-intel/yetzirah'
import { forwardRef, useRef, useEffect, useImperativeHandle } from 'react'

/**
 * Autocomplete container with input and options.
 *
 * @param {Object} props
 * @param {string|string[]} [props.value] - Controlled selected value(s)
 * @param {Function} [props.onChange] - Called when selection changes (value) => void
 * @param {Function} [props.onInputChange] - Called when input text changes (inputValue) => void
 * @param {Array<{value: string, label: string, disabled?: boolean}>} [props.options] - Options array
 * @param {boolean} [props.multiple] - Enable multi-select mode
 * @param {boolean} [props.loading] - Show loading state
 * @param {boolean} [props.filter] - Enable local filtering (default true)
 * @param {string} [props.placeholder] - Input placeholder
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} [props.loadingContent] - Custom loading content
 * @param {React.ReactNode} [props.children] - Option children (alternative to options prop)
 * @param {React.Ref} ref
 *
 * @example
 * const [value, setValue] = useState('')
 * <Autocomplete
 *   value={value}
 *   onChange={setValue}
 *   options={[
 *     { value: 'apple', label: 'Apple' },
 *     { value: 'banana', label: 'Banana' }
 *   ]}
 *   placeholder="Search fruits..."
 * />
 *
 * @example
 * // Multi-select
 * const [selected, setSelected] = useState([])
 * <Autocomplete
 *   multiple
 *   value={selected}
 *   onChange={setSelected}
 *   options={tags}
 * />
 */
export const Autocomplete = forwardRef(function Autocomplete(
  {
    value,
    onChange,
    onInputChange,
    options,
    multiple,
    loading,
    filter = true,
    placeholder,
    className,
    loadingContent = 'Loading...',
    children,
    ...props
  },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Sync controlled value
  useEffect(() => {
    const el = innerRef.current
    if (!el || value === undefined) return
    el.value = value
  }, [value])

  // Set options when prop changes
  useEffect(() => {
    const el = innerRef.current
    if (!el || !options) return
    // Check if setOptions is available (element must be initialized)
    if (typeof el.setOptions === 'function') {
      el.setOptions(options)
    }
  }, [options])

  // Event listeners
  useEffect(() => {
    const el = innerRef.current
    if (!el) return

    const handleChange = (e) => onChange?.(e.detail.value)
    const handleInputChange = (e) => onInputChange?.(e.detail.value)

    el.addEventListener('change', handleChange)
    el.addEventListener('input-change', handleInputChange)
    return () => {
      el.removeEventListener('change', handleChange)
      el.removeEventListener('input-change', handleInputChange)
    }
  }, [onChange, onInputChange])

  return (
    <ytz-autocomplete
      ref={innerRef}
      class={className}
      multiple={multiple || undefined}
      loading={loading || undefined}
      filter={filter ? undefined : 'false'}
      {...props}
    >
      <input slot="input" placeholder={placeholder} />
      <span slot="loading">{loadingContent}</span>
      {children}
    </ytz-autocomplete>
  )
})

/**
 * Option for Autocomplete.
 *
 * @param {Object} props
 * @param {string} props.value - Option value
 * @param {boolean} [props.disabled] - Option not selectable
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Option label
 * @param {React.Ref} ref
 *
 * @example
 * <Autocomplete>
 *   <Option value="red">Red</Option>
 *   <Option value="green" disabled>Green (unavailable)</Option>
 * </Autocomplete>
 */
export const Option = forwardRef(function Option(
  { value, disabled, className, children, ...props },
  ref
) {
  return (
    <ytz-option
      ref={ref}
      value={value}
      class={className}
      disabled={disabled || undefined}
      {...props}
    >
      {children}
    </ytz-option>
  )
})

// packages/vue/src/Autocomplete.vue
<template>
  <ytz-autocomplete
    :open="open || undefined"
    :multiple="multiple || undefined"
    :loading="loading || undefined"
    :filter="filter !== undefined ? filter : undefined"
    :class="$attrs.class"
    @change="handleChange"
    @input-change="handleInputChange"
    @open="handleOpen"
    @close="handleClose"
    @clear="handleClear"
    v-bind="$attrs"
  >
    <slot />
  </ytz-autocomplete>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-autocomplete Web Component.
 * Provides v-model for two-way binding with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/Autocomplete
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selectedValue">
 *     <input slot="input" placeholder="Search..." />
 *     <ytz-option value="apple">Apple</ytz-option>
 *     <ytz-option value="banana">Banana</ytz-option>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selectedValues" multiple>
 *     <input slot="input" placeholder="Select multiple..." />
 *     <ytz-option value="a">Option A</ytz-option>
 *     <ytz-option value="b">Option B</ytz-option>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <Autocomplete v-model="value" :open="isOpen" :loading="isLoading" :filter="false">
 *     <input slot="input" placeholder="Custom filtering..." />
 *     <ytz-option v-for="item in items" :key="item.id" :value="item.id">
 *       {{ item.label }}
 *     </ytz-option>
 *   </Autocomplete>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the Autocomplete component
 */
interface Props {
  /**
   * The selected value (two-way bindable via v-model)
   * String for single-select, array of strings for multi-select
   */
  modelValue?: string | string[]

  /**
   * Whether the dropdown is open
   */
  open?: boolean

  /**
   * Enable multi-select mode
   */
  multiple?: boolean

  /**
   * Show loading state
   */
  loading?: boolean

  /**
   * Enable automatic filtering of options (default: true)
   */
  filter?: boolean
}

/**
 * Emits for the Autocomplete component
 */
interface Emits {
  /**
   * Emitted when selected value changes
   * @param value The new selected value(s)
   */
  (e: 'update:modelValue', value: string | string[]): void

  /**
   * Native change event with detail.value and detail.option
   * @param event The change event
   */
  (e: 'change', event: CustomEvent): void

  /**
   * Emitted when input value changes (typing)
   * @param event Event with detail.value (input text)
   */
  (e: 'input-change', event: CustomEvent): void

  /**
   * Emitted when dropdown opens
   * @param event The open event
   */
  (e: 'open', event: Event): void

  /**
   * Emitted when dropdown closes
   * @param event The close event
   */
  (e: 'close', event: Event): void

  /**
   * Emitted when selection is cleared
   * @param event The clear event
   */
  (e: 'clear', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const value = defineModel<string | string[]>('modelValue', { default: '' })

/**
 * Handle change events from the underlying web component
 */
function handleChange(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && detail.value !== undefined) {
    value.value = detail.value
  }
  emit('change', event as CustomEvent)
}

/**
 * Handle input-change events (typing in the input)
 */
function handleInputChange(event: Event) {
  emit('input-change', event as CustomEvent)
}

/**
 * Handle open event
 */
function handleOpen(event: Event) {
  emit('open', event)
}

/**
 * Handle close event
 */
function handleClose(event: Event) {
  emit('close', event)
}

/**
 * Handle clear event
 */
function handleClear(event: Event) {
  value.value = ''
  emit('clear', event)
}
</script>
