// packages/svelte/src/Button.svelte
<!--
  Svelte wrapper for ytz-button Web Component.
  Polymorphic button/anchor that renders <a> when href provided, <button> otherwise.

  @module @grimoire/yetzirah-svelte/Button
-->
<script>
  import '@grimoire/yetzirah-core'

  /**
   * Button component - polymorphic button/anchor.
   * Renders as <a> when href is provided, <button> otherwise.
   *
   * @slot default - Button text or content
   *
   * @example
   * <Button on:click={handleSubmit}>Submit</Button>
   *
   * @example
   * <Button href="/dashboard">Go to Dashboard</Button>
   *
   * @example
   * <Button disabled>Disabled Button</Button>
   *
   * @example
   * <Button type="submit">Submit Form</Button>
   */

  /** Optional href for navigation (makes it an anchor) */
  export let href = undefined

  /** Disable button (only applies when href is not set) */
  export let disabled = false

  /** Button type attribute (only applies when href is not set) */
  export let type = 'button'
</script>

<ytz-button
  href={href || undefined}
  {disabled}
  {type}
  class={$$props.class}
  {...$$restProps}
  on:click
>
  <slot />
</ytz-button>

<style>
  /* Component inherits styles from web component */
</style>

// packages/vue/src/Button.vue
<template>
  <ytz-button
    :href="href"
    :disabled="disabled"
    :type="type"
    :class="$attrs.class"
    @click="emit('click', $event)"
    v-bind="$attrs"
  >
    <slot />
  </ytz-button>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-button Web Component.
 * Polymorphic button/anchor that renders <a> when href provided, <button> otherwise.
 *
 * @module @grimoire/yetzirah-vue/Button
 *
 * @example
 * <template>
 *   <Button @click="handleSubmit">Submit</Button>
 * </template>
 *
 * @example
 * <template>
 *   <Button href="/dashboard">Dashboard</Button>
 * </template>
 *
 * @example
 * <template>
 *   <Button type="submit" disabled>Save</Button>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the Button component
 */
interface Props {
  /**
   * Optional href for link variant (renders as <a> instead of <button>)
   */
  href?: string

  /**
   * Whether the button is disabled (only applies to button variant)
   */
  disabled?: boolean

  /**
   * Button type attribute (only applies to button variant)
   * @default 'button'
   */
  type?: 'button' | 'submit' | 'reset'
}

/**
 * Emits for the Button component
 */
interface Emits {
  /**
   * Emitted when the button is clicked
   * @param event The click event
   */
  (e: 'click', event: MouseEvent): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()
</script>
