// packages/svelte/src/Chip.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-chip Web Component.
	 * Provides a deletable tag/label with keyboard support.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Chip deletable on:delete={removeTag}>JavaScript</Chip>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Chip disabled>Read-only tag</Chip>
	 * ```
	 */

	let element: HTMLElement & { deletable?: boolean; disabled?: boolean }

	/** Show delete button */
	export let deletable = false

	/** Disable chip interactions */
	export let disabled = false

	/**
	 * Handle delete events from the web component
	 * @private
	 */
	function handleDelete(event: CustomEvent<{ chip: HTMLElement }>) {
		// Event is dispatched by the web component
		// Just forward it through Svelte's event system
	}

	/**
	 * Sync deletable state to web component
	 * @private
	 */
	$: if (element) {
		element.deletable = deletable
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	onMount(() => {
		if (element) {
			element.addEventListener('delete', handleDelete)

			return () => {
				element.removeEventListener('delete', handleDelete)
			}
		}
	})
</script>

<ytz-chip
	bind:this={element}
	class={$$restProps.class || ''}
	{deletable}
	{disabled}
	on:delete
	{...$$restProps}
>
	<slot />
</ytz-chip>

<style>
	:global(ytz-chip) {
		display: inline-flex;
		align-items: center;
	}
</style>

// packages/vue/src/Chip.vue
<template>
  <ytz-chip
    :deletable="deletable || undefined"
    :disabled="disabled || undefined"
    @delete="handleDelete"
    v-bind="attrs"
    :class="$attrs.class"
  >
    <slot />
  </ytz-chip>
</template>

<script setup lang="ts">
import '@grimoire-intel/yetzirah'
import { useAttrs } from 'vue'

/**
 * Chip component - deletable tag/label.
 *
 * @example
 * <Chip deletable @delete="removeTag">
 *   JavaScript
 * </Chip>
 *
 * @example
 * <Chip disabled>Read-only tag</Chip>
 */

interface Props {
  /** Show delete button */
  deletable?: boolean
  /** Disable chip interactions */
  disabled?: boolean
}

defineProps<Props>()

const emit = defineEmits<{
  /** Emitted when chip is deleted (via button click or keyboard) */
  delete: [event: CustomEvent]
}>()

const attrs = useAttrs()

const handleDelete = (event: Event) => {
  emit('delete', event as CustomEvent)
}
</script>
