// packages/angular/src/lib/listbox-option.component.ts
import {
  Component,
  Input,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-option Web Component (used within ytz-listbox).
 * Represents an individual option in the listbox.
 *
 * @example
 * <ytz-listbox>
 *   <ytz-option value="opt1">Option 1</ytz-option>
 *   <ytz-option value="opt2" [disabled]="true">Option 2 (disabled)</ytz-option>
 *   <ytz-option value="opt3" [selected]="true">Option 3 (selected)</ytz-option>
 * </ytz-listbox>
 */
@Component({
  selector: 'ytz-option',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class ListboxOptionComponent {
  /**
   * The value of this option
   */
  @Input() value: string = '';

  /**
   * Whether this option is disabled
   */
  @Input() disabled: boolean = false;

  /**
   * Whether this option is selected
   */
  @Input() selected: boolean = false;
}

// packages/vue/src/ListboxOption.vue
<template>
  <ytz-option
    :value="value"
    :disabled="disabled || undefined"
    :selected="selected || undefined"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-option>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-option Web Component (used within Listbox).
 * Represents a selectable option in a listbox.
 *
 * @module @grimoire/yetzirah-vue/ListboxOption
 *
 * @example
 * <template>
 *   <Listbox v-model="selected">
 *     <ListboxOption value="1">Option 1</ListboxOption>
 *     <ListboxOption value="2">Option 2</ListboxOption>
 *     <ListboxOption value="3" disabled>Option 3 (disabled)</ListboxOption>
 *   </Listbox>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the ListboxOption component
 */
interface Props {
  /**
   * The value of this option
   */
  value?: string

  /**
   * Whether the option is disabled
   */
  disabled?: boolean

  /**
   * Whether the option is selected (managed by parent listbox)
   */
  selected?: boolean
}

defineProps<Props>()
</script>
