// packages/svelte/src/Listbox.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-listbox Web Component.
	 * Provides keyboard-navigable list selection with single/multi-select modes.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Listbox bind:value={selected}>
	 *   <ListboxOption value="opt1">Option 1</ListboxOption>
	 *   <ListboxOption value="opt2">Option 2</ListboxOption>
	 * </Listbox>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Listbox multiple bind:value={selectedItems}>
	 *   <ListboxOption value="a">Option A</ListboxOption>
	 *   <ListboxOption value="b">Option B</ListboxOption>
	 * </Listbox>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Listbox disabled>
	 *   <ListboxOption value="opt1">Option 1</ListboxOption>
	 * </Listbox>
	 * ```
	 */

	let element: HTMLElement & {
		multiple?: boolean
		disabled?: boolean
		value?: string | string[]
		clear?: () => void
		selectAll?: () => void
	}

	/** Controlled value state (string for single-select, array for multi-select) */
	export let value: string | string[] = ''

	/** Enable multi-select mode */
	export let multiple: boolean = false

	/** Disable listbox interactions */
	export let disabled: boolean = false

	/**
	 * Handle change events from the web component
	 * @private
	 */
	function handleChange(event: CustomEvent<{ value: string | string[]; option: HTMLElement }>) {
		if (event.detail) {
			value = event.detail.value
		}
	}

	/**
	 * Handle clear events from the web component
	 * @private
	 */
	function handleClear() {
		value = multiple ? [] : ''
	}

	/**
	 * Sync value to web component
	 * @private
	 */
	$: if (element && element.value !== value) {
		element.value = value
	}

	/**
	 * Sync multiple state to web component
	 * @private
	 */
	$: if (element) {
		element.multiple = multiple
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	onMount(() => {
		if (element) {
			element.addEventListener('change', handleChange)
			element.addEventListener('clear', handleClear)

			return () => {
				element.removeEventListener('change', handleChange)
				element.removeEventListener('clear', handleClear)
			}
		}
	})

	// Expose methods for programmatic control
	export function clear() {
		element?.clear?.()
	}

	export function selectAll() {
		element?.selectAll?.()
	}
</script>

<ytz-listbox
	bind:this={element}
	class={$$restProps.class || ''}
	{multiple}
	{disabled}
	on:change
	on:clear
	{...$$restProps}
>
	<slot />
</ytz-listbox>

<style>
	:global(ytz-listbox) {
		display: block;
		border: 1px solid var(--color-border, #ccc);
		border-radius: 4px;
		padding: 4px;
		background: white;
		max-height: 300px;
		overflow-y: auto;
	}

	:global(ytz-listbox:focus) {
		outline: none;
		border-color: var(--color-primary, #1976d2);
		box-shadow: 0 0 0 2px rgba(25, 118, 210, 0.1);
	}

	:global(ytz-listbox[disabled]) {
		opacity: 0.6;
		cursor: not-allowed;
		background-color: var(--color-background-disabled, #f5f5f5);
	}
</style>

// packages/vue/src/Listbox.vue
<template>
  <ytz-listbox
    :multiple="multiple || undefined"
    :disabled="disabled || undefined"
    :class="$attrs.class"
    @change="handleChange"
    v-bind="$attrs"
  >
    <slot />
  </ytz-listbox>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-listbox Web Component.
 * Provides v-model for two-way binding with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/Listbox
 *
 * @example
 * <template>
 *   <Listbox v-model="selectedValue">
 *     <ytz-option value="1">Option 1</ytz-option>
 *     <ytz-option value="2">Option 2</ytz-option>
 *   </Listbox>
 * </template>
 *
 * @example
 * <template>
 *   <Listbox v-model="selectedValues" multiple>
 *     <ytz-option value="a">Option A</ytz-option>
 *     <ytz-option value="b">Option B</ytz-option>
 *     <ytz-option value="c">Option C</ytz-option>
 *   </Listbox>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the Listbox component
 */
interface Props {
  /**
   * The selected value (two-way bindable via v-model)
   * Single value when multiple=false, array when multiple=true
   */
  modelValue?: string | string[]

  /**
   * Enable multi-select mode
   */
  multiple?: boolean

  /**
   * Whether the listbox is disabled
   */
  disabled?: boolean
}

/**
 * Emits for the Listbox component
 */
interface Emits {
  /**
   * Emitted when selection changes
   * @param value The new selected value(s)
   */
  (e: 'update:modelValue', value: string | string[]): void

  /**
   * Native change event with detail.value
   * @param event The change event
   */
  (e: 'change', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const value = defineModel<string | string[]>('modelValue', { default: '' })

/**
 * Handle change events from the underlying web component
 */
function handleChange(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && detail.value !== undefined) {
    value.value = detail.value
  }
  emit('change', event)
}
</script>
