// packages/angular/src/lib/menu-trigger.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy
} from '@angular/core';

/**
 * Angular helper component for menu trigger slot.
 * Wraps content that should trigger the menu.
 *
 * @example
 * <ytz-menu>
 *   <ytz-menu-trigger>
 *     <button>Open Menu</button>
 *   </ytz-menu-trigger>
 *   <ytz-menuitem>Edit</ytz-menuitem>
 * </ytz-menu>
 */
@Component({
  selector: 'ytz-menu-trigger',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <div slot="trigger">
      <ng-content></ng-content>
    </div>
  `,
  styles: []
})
export class MenuTriggerComponent {}

// packages/vue/src/MenuTrigger.vue
<template>
  <ytz-menu-trigger
    v-bind="$attrs"
    :class="$attrs.class"
  >
    <slot />
  </ytz-menu-trigger>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-menu-trigger Web Component.
 * Trigger element for opening a Menu component.
 *
 * @module @grimoire/yetzirah-vue/MenuTrigger
 *
 * @example
 * <template>
 *   <Menu>
 *     <MenuTrigger>
 *       <button>Open Menu</button>
 *     </MenuTrigger>
 *     <MenuItem>Edit</MenuItem>
 *     <MenuItem>Delete</MenuItem>
 *   </Menu>
 * </template>
 */

import '@grimoire/yetzirah-core'
</script>
