// packages/svelte/src/MenuItem.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-menuitem Web Component.
	 * Individual menu item with select event.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <MenuItem on:select={handleEdit}>Edit</MenuItem>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <MenuItem value="delete" disabled on:select={handleAction}>Delete</MenuItem>
	 * ```
	 */

	let element: HTMLElement & { disabled?: boolean; value?: string }

	/** Disabled state */
	export let disabled = false

	/** Optional value for select event */
	export let value: string | undefined = undefined

	/**
	 * Handle select events from the web component
	 * @private
	 */
	function handleSelect(event: CustomEvent<{ value: string }>) {
		// Event is dispatched by the web component
		// Just forward it through Svelte's event system
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	/**
	 * Sync value to web component
	 * @private
	 */
	$: if (element && value !== undefined) {
		element.value = value
	}

	onMount(() => {
		if (element) {
			element.addEventListener('select', handleSelect)

			return () => {
				element.removeEventListener('select', handleSelect)
			}
		}
	})
</script>

<ytz-menuitem
	bind:this={element}
	class={$$restProps.class || ''}
	disabled={disabled || undefined}
	value={value}
	on:select
	{...$$restProps}
>
	<slot />
</ytz-menuitem>

<style>
	:global(ytz-menuitem) {
		display: block;
	}
</style>

// packages/vue/src/MenuItem.vue
<template>
  <ytz-menu-item
    :value="value"
    :disabled="disabled || undefined"
    @click="emit('click', $event)"
    v-bind="$attrs"
    :class="$attrs.class"
  >
    <slot />
  </ytz-menu-item>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-menu-item Web Component.
 * Individual menu item within a Menu component.
 *
 * @module @grimoire-intel/yetzirah-vue/MenuItem
 *
 * @example
 * <template>
 *   <Menu>
 *     <template #trigger>
 *       <button>Open Menu</button>
 *     </template>
 *     <MenuItem value="edit" @click="handleEdit">Edit</MenuItem>
 *     <MenuItem value="delete" @click="handleDelete">Delete</MenuItem>
 *     <MenuItem disabled>Archive</MenuItem>
 *   </Menu>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the MenuItem component
 */
interface Props {
  /**
   * Value associated with this menu item
   */
  value?: string

  /**
   * Whether the menu item is disabled
   */
  disabled?: boolean
}

/**
 * Emits for the MenuItem component
 */
interface Emits {
  /**
   * Emitted when the menu item is clicked
   * @param event The click event
   */
  (e: 'click', event: MouseEvent): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()
</script>
