// packages/angular/src/lib/menu.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnDestroy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-menu Web Component.
 * Provides a dropdown menu with keyboard navigation.
 *
 * @example
 * <ytz-menu [open]="isOpen" (openEvent)="onOpen()" (closeEvent)="onClose()">
 *   <button slot="trigger">Open Menu</button>
 *   <ytz-menuitem>Edit</ytz-menuitem>
 *   <ytz-menuitem>Delete</ytz-menuitem>
 * </ytz-menu>
 *
 * @example
 * <ytz-menu placement="bottom-start">
 *   <ytz-menu-trigger>Actions</ytz-menu-trigger>
 *   <ytz-menuitem value="edit">Edit</ytz-menuitem>
 *   <ytz-menuitem [disabled]="true">Archive</ytz-menuitem>
 * </ytz-menu>
 */
@Component({
  selector: 'ytz-menu',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class MenuComponent implements AfterViewInit, OnDestroy {
  /**
   * Whether the menu is open
   */
  @Input() open: boolean = false;

  /**
   * Menu placement relative to trigger
   */
  @Input() placement: string = 'bottom-start';

  /**
   * Emitted when the menu opens
   */
  @Output() openEvent = new EventEmitter<CustomEvent>();

  /**
   * Emitted when the menu closes
   */
  @Output() closeEvent = new EventEmitter<CustomEvent>();

  @ViewChild('menuElement', { read: ElementRef }) menuElement!: ElementRef;

  private openHandler = (e: Event) => {
    this.openEvent.emit(e as CustomEvent);
  };

  private closeHandler = (e: Event) => {
    this.closeEvent.emit(e as CustomEvent);
  };

  ngAfterViewInit() {
    this.setupEventListeners();
  }

  ngOnDestroy() {
    this.removeEventListeners();
  }

  private setupEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.addEventListener('open', this.openHandler);
      el.addEventListener('close', this.closeHandler);
    }
  }

  private removeEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.removeEventListener('open', this.openHandler);
      el.removeEventListener('close', this.closeHandler);
    }
  }

  private getNativeElement() {
    // For standalone components with template, get the host element itself
    // since we're using selector: 'ytz-menu'
    if (typeof window !== 'undefined') {
      return document.querySelector('ytz-menu');
    }
    return null;
  }
}

// packages/vue/src/Menu.vue
<template>
  <ytz-menu
    :open="open || undefined"
    :placement="placement"
    @open="handleOpen"
    @close="handleClose"
    v-bind="$attrs"
    :class="$attrs.class"
  >
    <slot name="trigger" slot="trigger" />
    <slot />
  </ytz-menu>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-menu Web Component.
 * Dropdown menu with keyboard navigation, positioned relative to trigger.
 *
 * @module @grimoire/yetzirah-vue/Menu
 *
 * @example
 * <template>
 *   <Menu>
 *     <template #trigger>
 *       <button>Open Menu</button>
 *     </template>
 *     <MenuItem>Edit</MenuItem>
 *     <MenuItem>Delete</MenuItem>
 *   </Menu>
 * </template>
 *
 * @example
 * <template>
 *   <Menu :open="isOpen" placement="bottom-start" @close="handleClose">
 *     <template #trigger>
 *       <button>Actions</button>
 *     </template>
 *     <MenuItem value="edit">Edit</MenuItem>
 *     <MenuItem disabled>Archive</MenuItem>
 *   </Menu>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the Menu component
 */
interface Props {
  /**
   * Controlled open state
   */
  open?: boolean

  /**
   * Menu placement relative to trigger
   * @default 'bottom-start'
   */
  placement?: string
}

/**
 * Emits for the Menu component
 */
interface Emits {
  /**
   * Emitted when menu opens
   * @param event The open event
   */
  (e: 'open', event: CustomEvent): void

  /**
   * Emitted when menu closes
   * @param event The close event
   */
  (e: 'close', event: CustomEvent): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

/**
 * Handle open events from the underlying web component
 */
function handleOpen(event: Event) {
  emit('open', event as CustomEvent)
}

/**
 * Handle close events from the underlying web component
 */
function handleClose(event: Event) {
  emit('close', event as CustomEvent)
}
</script>
