// packages/angular/src/lib/tab.component.ts
import {
  Component,
  Input,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-tab Web Component.
 * Represents an individual tab within a ytz-tabs component.
 *
 * @example
 * <ytz-tabs>
 *   <ytz-tab panel="tab1">Account</ytz-tab>
 *   <ytz-tab panel="tab2">Settings</ytz-tab>
 *   <ytz-tabpanel id="tab1">Account content</ytz-tabpanel>
 *   <ytz-tabpanel id="tab2">Settings content</ytz-tabpanel>
 * </ytz-tabs>
 */
@Component({
  selector: 'ytz-tab',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class TabComponent {
  /**
   * The ID of the associated tab panel
   */
  @Input() panel: string = '';
}

// packages/vue/src/Tab.vue
<template>
  <ytz-tab
    :panel="panel"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-tab>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-tab Web Component.
 * Represents a single tab button within a Tabs component.
 *
 * @module @grimoire/yetzirah-vue/Tab
 *
 * @example
 * <template>
 *   <Tabs v-model="selectedTab">
 *     <Tab panel="home">Home</Tab>
 *     <Tab panel="about">About</Tab>
 *     <TabPanel id="home">Home content</TabPanel>
 *     <TabPanel id="about">About content</TabPanel>
 *   </Tabs>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the Tab component
 */
interface Props {
  /**
   * The ID of the TabPanel this tab controls (required)
   */
  panel: string
}

defineProps<Props>()
</script>
