// packages/angular/src/lib/theme-toggle.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  AfterViewInit,
  OnDestroy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-theme-toggle Web Component.
 * Provides theme switching with persistence and system preference detection.
 *
 * @example
 * <ytz-theme-toggle (themeChange)="onThemeChange($event)"></ytz-theme-toggle>
 *
 * @example
 * <ytz-theme-toggle [theme]="'dark'" (themeChange)="onThemeChange($event)">
 *   Dark mode
 * </ytz-theme-toggle>
 */
@Component({
  selector: 'ytz-theme-toggle',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class ThemeToggleComponent implements AfterViewInit, OnDestroy {
  /**
   * Current theme ('light' | 'dark')
   */
  @Input() theme: 'light' | 'dark' = 'light';

  /**
   * Emitted when the theme changes
   */
  @Output() themeChange = new EventEmitter<CustomEvent>();

  private themeChangeHandler = (e: Event) => {
    this.themeChange.emit(e as CustomEvent);
  };

  ngAfterViewInit() {
    this.setupEventListeners();
  }

  ngOnDestroy() {
    this.removeEventListeners();
  }

  private setupEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.addEventListener('themechange', this.themeChangeHandler);
    }
  }

  private removeEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.removeEventListener('themechange', this.themeChangeHandler);
    }
  }

  private getNativeElement() {
    // For standalone components with template, get the host element itself
    // since we're using selector: 'ytz-theme-toggle'
    if (typeof window !== 'undefined') {
      return document.querySelector('ytz-theme-toggle');
    }
    return null;
  }
}

// packages/vue/src/ThemeToggle.vue
<template>
  <ytz-theme-toggle
    ref="rootRef"
    :class="class"
    :storage-key="storageKey"
    :no-persist="noPersist || undefined"
    v-bind="$attrs"
    @themechange="handleThemeChange"
  >
    <slot />
  </ytz-theme-toggle>
</template>

<script setup lang="ts">
/**
 * Vue wrapper for ytz-theme-toggle Web Component.
 * Provides theme switching with persistence and system preference detection.
 *
 * @module @grimoire/yetzirah-vue/ThemeToggle
 *
 * @example
 * // Basic usage
 * <ThemeToggle @themechange="(e) => console.log(e.detail.theme)" />
 *
 * @example
 * // With custom storage key
 * <ThemeToggle storageKey="my-app-theme">Dark mode</ThemeToggle>
 *
 * @example
 * // Without persistence
 * <ThemeToggle no-persist @themechange="(e) => console.log(e.detail.theme)">
 *   Toggle theme
 * </ThemeToggle>
 */

import '@grimoire/yetzirah-core'
import { ref } from 'vue'
import type { YetzirahComponentProps } from './types'

interface ThemeToggleProps extends YetzirahComponentProps {
  /**
   * The current theme ('light' or 'dark')
   */
  theme?: 'light' | 'dark'

  /**
   * localStorage key for persistence (default: 'yetzirah-theme')
   */
  storageKey?: string

  /**
   * Disable localStorage persistence
   */
  noPersist?: boolean
}

interface ThemeChangeEvent extends CustomEvent {
  detail: {
    theme: 'light' | 'dark'
    isDark: boolean
  }
}

defineProps<ThemeToggleProps>()

const rootRef = ref<HTMLElement | null>(null)

const emit = defineEmits<{
  /**
   * Emitted when theme changes
   */
  themechange: [event: ThemeChangeEvent]
}>()

const handleThemeChange = (e: Event) => {
  emit('themechange', e as ThemeChangeEvent)
}
</script>
