// packages/svelte/src/Toggle.svelte
<script lang="ts">
	import '@grimoire-intel/yetzirah'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-toggle Web Component.
	 * Provides Svelte-idiomatic two-way binding with bind:checked.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <Toggle bind:checked={enabled}>Dark mode</Toggle>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <Toggle bind:checked={enabled} disabled>Premium feature</Toggle>
	 * ```
	 */

	let element: HTMLElement & { checked?: boolean; disabled?: boolean }

	/** Controlled checked state */
	export let checked = false

	/** Disabled state */
	export let disabled = false

	/**
	 * Handle change events from the web component
	 * @private
	 */
	function handleChange(event: CustomEvent<{ checked: boolean }>) {
		if (event.detail) {
			checked = event.detail.checked
		}
	}

	/**
	 * Sync checked state to web component
	 * @private
	 */
	$: if (element) {
		element.checked = checked
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	onMount(() => {
		if (element) {
			element.addEventListener('change', handleChange)

			return () => {
				element.removeEventListener('change', handleChange)
			}
		}
	})
</script>

<ytz-toggle
	bind:this={element}
	class={$$restProps.class || ''}
	{disabled}
	on:change
	{...$$restProps}
>
	<slot />
</ytz-toggle>

<style>
	:global(ytz-toggle) {
		display: inline-block;
	}
</style>

// packages/vue/src/Toggle.vue
<template>
  <ytz-toggle
    :checked="checked"
    :disabled="disabled"
    :class="$attrs.class"
    @change="handleChange"
    v-bind="$attrs"
  >
    <slot />
  </ytz-toggle>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-toggle Web Component.
 * Provides v-model:checked for two-way binding with full TypeScript support.
 *
 * @module @grimoire-intel/yetzirah-vue/Toggle
 *
 * @example
 * <template>
 *   <Toggle v-model:checked="enabled" />
 * </template>
 *
 * @example
 * <template>
 *   <Toggle v-model:checked="darkMode" disabled>
 *     Dark mode
 *   </Toggle>
 * </template>
 */

import '@grimoire-intel/yetzirah'

/**
 * Props for the Toggle component
 */
interface Props {
  /**
   * The checked state (two-way bindable via v-model:checked)
   */
  checked?: boolean

  /**
   * Whether the toggle is disabled
   */
  disabled?: boolean
}

/**
 * Emits for the Toggle component
 */
interface Emits {
  /**
   * Emitted when toggle state changes
   * @param value The new checked state
   */
  (e: 'update:checked', value: boolean): void

  /**
   * Native change event with detail.checked
   * @param event The change event
   */
  (e: 'change', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const checked = defineModel<boolean>('checked', { default: false })

/**
 * Handle change events from the underlying web component
 */
function handleChange(event: Event) {
  const detail = (event as CustomEvent).detail
  if (detail && typeof detail.checked === 'boolean') {
    checked.value = detail.checked
  }
  emit('change', event)
}
</script>
