// packages/react/src/tooltip.js
/**
 * React wrapper for ytz-tooltip Web Component.
 * Provides positioned hint text on hover/focus.
 *
 * @module @grimoire/yetzirah-react/tooltip
 */

import '@grimoire/yetzirah-core'
import { forwardRef, useRef, useEffect, useImperativeHandle } from 'react'

/**
 * Tooltip component - positioned hint text on hover/focus.
 *
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.content - Tooltip content (text or elements)
 * @param {'top'|'bottom'|'left'|'right'} [props.placement='top'] - Tooltip position
 * @param {number} [props.delay=0] - Show delay in milliseconds
 * @param {number} [props.offset=8] - Gap between trigger and tooltip
 * @param {Function} [props.onShow] - Callback when tooltip shows
 * @param {Function} [props.onHide] - Callback when tooltip hides
 * @param {string} [props.className] - CSS classes for tooltip content
 * @param {React.ReactNode} props.children - Trigger element
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Tooltip content="Helpful hint" placement="top">
 *   <Button>Hover me</Button>
 * </Tooltip>
 *
 * @example
 * // With callbacks
 * <Tooltip
 *   content="Tracked tooltip"
 *   onShow={() => console.log('shown')}
 *   onHide={() => console.log('hidden')}
 * >
 *   <button>Hover me</button>
 * </Tooltip>
 */
export const Tooltip = forwardRef(function Tooltip(
  { content, placement, delay, offset, onShow, onHide, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Bridge show/hide events
  useEffect(() => {
    const el = innerRef.current
    if (!el) return

    const handleShow = () => onShow?.()
    const handleHide = () => onHide?.()

    el.addEventListener('show', handleShow)
    el.addEventListener('hide', handleHide)

    return () => {
      el.removeEventListener('show', handleShow)
      el.removeEventListener('hide', handleHide)
    }
  }, [onShow, onHide])

  return (
    <ytz-tooltip
      ref={innerRef}
      placement={placement}
      delay={delay}
      offset={offset}
      {...props}
    >
      {children}
      <span slot="content" className={className}>
        {content}
      </span>
    </ytz-tooltip>
  )
})

// packages/vue/src/Tooltip.vue
<template>
  <ytz-tooltip
    :placement="placement"
    :delay="delay"
    :offset="offset"
    :class="$attrs.class"
    v-bind="$attrs"
    @show="handleShow"
    @hide="handleHide"
  >
    <slot />
    <template v-if="content || $slots.content">
      <span v-if="content" slot="content" :class="contentClass">{{ content }}</span>
      <slot v-else name="content" />
    </template>
  </ytz-tooltip>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-tooltip Web Component.
 * Provides positioned hint text on hover/focus with full TypeScript support.
 *
 * @module @grimoire/yetzirah-vue/Tooltip
 *
 * @example
 * <template>
 *   <Tooltip content="Helpful hint" placement="top">
 *     <button>Hover me</button>
 *   </Tooltip>
 * </template>
 *
 * @example
 * <template>
 *   <Tooltip placement="bottom" :delay="200">
 *     <button>Hover me</button>
 *     <template #content>
 *       <strong>Rich content</strong> tooltip
 *     </template>
 *   </Tooltip>
 * </template>
 *
 * @example
 * <template>
 *   <Tooltip
 *     content="Tracked tooltip"
 *     @show="onTooltipShow"
 *     @hide="onTooltipHide"
 *   >
 *     <button>Hover me</button>
 *   </Tooltip>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the Tooltip component
 */
interface Props {
  /**
   * Tooltip content as text (for simple tooltips)
   */
  content?: string

  /**
   * Tooltip position relative to trigger
   */
  placement?: 'top' | 'bottom' | 'left' | 'right'

  /**
   * Show delay in milliseconds
   */
  delay?: number

  /**
   * Gap between trigger and tooltip
   */
  offset?: number

  /**
   * CSS classes for tooltip content (when using content prop)
   */
  contentClass?: string
}

/**
 * Emits for the Tooltip component
 */
interface Emits {
  /**
   * Emitted when tooltip shows
   * @param event The show event
   */
  (e: 'show', event: Event): void

  /**
   * Emitted when tooltip hides
   * @param event The hide event
   */
  (e: 'hide', event: Event): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

/**
 * Handle show events from the underlying web component
 */
function handleShow(event: Event) {
  emit('show', event)
}

/**
 * Handle hide events from the underlying web component
 */
function handleHide(event: Event) {
  emit('hide', event)
}
</script>
