// packages/vue/src/AutocompleteOption.vue
<template>
  <ytz-option
    :value="value"
    :disabled="disabled || undefined"
    :selected="selected || undefined"
    :class="$attrs.class"
    v-bind="$attrs"
  >
    <slot />
  </ytz-option>
</template>

<script setup lang="ts">
/**
 * Vue 3 wrapper for ytz-option Web Component (used within Autocomplete/Listbox/Select).
 * Provides Vue-idiomatic API with full TypeScript support.
 *
 * @module @grimoire/yetzirah-vue/AutocompleteOption
 *
 * @example
 * <template>
 *   <Autocomplete v-model="selected">
 *     <input slot="input" placeholder="Search..." />
 *     <AutocompleteOption value="apple">Apple</AutocompleteOption>
 *     <AutocompleteOption value="banana">Banana</AutocompleteOption>
 *     <AutocompleteOption value="orange" disabled>Orange (out of stock)</AutocompleteOption>
 *   </Autocomplete>
 * </template>
 *
 * @example
 * <template>
 *   <AutocompleteOption :value="item.id" :selected="item.selected">
 *     {{ item.label }}
 *   </AutocompleteOption>
 * </template>
 */

import '@grimoire/yetzirah-core'

/**
 * Props for the AutocompleteOption component
 */
interface Props {
  /**
   * The option value
   */
  value?: string

  /**
   * Whether the option is disabled
   */
  disabled?: boolean

  /**
   * Whether the option is selected (managed by parent Autocomplete)
   */
  selected?: boolean
}

defineProps<Props>()
</script>

// packages/angular/src/lib/autocomplete-option.component.ts
import {
  Component,
  Input,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-option Web Component (used within ytz-autocomplete).
 * Represents an individual option in the autocomplete dropdown.
 *
 * @example
 * <ytz-autocomplete>
 *   <input slot="input" placeholder="Search...">
 *   <ytz-option value="apple">Apple</ytz-option>
 *   <ytz-option value="banana" [disabled]="true">Banana (Out of stock)</ytz-option>
 * </ytz-autocomplete>
 */
@Component({
  selector: 'ytz-option',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class AutocompleteOptionComponent {
  /**
   * The value of this option
   */
  @Input() value: string = '';

  /**
   * Whether this option is disabled
   */
  @Input() disabled: boolean = false;

  /**
   * Whether this option is selected
   */
  @Input() selected: boolean = false;
}
