// packages/react/src/chip.js
/**
 * React wrapper for ytz-chip Web Component.
 * Provides deletable tag/label with keyboard support.
 *
 * @module @grimoire/yetzirah-react/chip
 */

import '@grimoire/yetzirah-core'
import { forwardRef, useRef, useImperativeHandle, useEffect, useCallback } from 'react'

/**
 * Chip component - deletable tag/label.
 *
 * @param {Object} props - Component props
 * @param {boolean} [props.deletable] - Show delete button
 * @param {Function} [props.onDelete] - Delete handler (receives event with detail.chip)
 * @param {boolean} [props.disabled] - Disable chip interactions
 * @param {string} [props.className] - CSS classes
 * @param {React.ReactNode} props.children - Chip content
 * @param {React.Ref} ref - Forwarded ref
 * @returns {JSX.Element}
 *
 * @example
 * <Chip deletable onDelete={() => removeTag(id)}>
 *   JavaScript
 * </Chip>
 *
 * @example
 * <Chip disabled>Read-only tag</Chip>
 */
export const Chip = forwardRef(function Chip(
  { deletable, onDelete, disabled, className, children, ...props },
  ref
) {
  const innerRef = useRef(null)

  useImperativeHandle(ref, () => innerRef.current)

  // Handle delete events from the web component
  const handleDelete = useCallback((e) => {
    if (onDelete) {
      onDelete(e)
    }
  }, [onDelete])

  // Set up event listener for delete events
  useEffect(() => {
    const el = innerRef.current
    if (!el) return

    el.addEventListener('delete', handleDelete)
    return () => el.removeEventListener('delete', handleDelete)
  }, [handleDelete])

  return (
    <ytz-chip
      ref={innerRef}
      class={className}
      deletable={deletable || undefined}
      disabled={disabled || undefined}
      {...props}
    >
      {children}
    </ytz-chip>
  )
})

// packages/angular/src/lib/chip.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnDestroy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-chip Web Component.
 * Provides a deletable tag/label with keyboard support.
 *
 * @example
 * <ytz-chip [deletable]="true" (delete)="onDelete()">Tag</ytz-chip>
 *
 * @example
 * <ytz-chip [disabled]="true">Read-only tag</ytz-chip>
 */
@Component({
  selector: 'ytz-chip',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class ChipComponent implements AfterViewInit, OnDestroy {
  /**
   * Show delete button on the chip
   */
  @Input() deletable: boolean = false;

  /**
   * Disable chip interactions
   */
  @Input() disabled: boolean = false;

  /**
   * Emitted when the chip delete button is clicked or Delete/Backspace key is pressed
   */
  @Output() delete = new EventEmitter<CustomEvent>();

  @ViewChild('chipElement', { read: ElementRef }) chipElement!: ElementRef;

  private deleteHandler = (e: Event) => {
    this.delete.emit(e as CustomEvent);
  };

  ngAfterViewInit() {
    this.setupEventListeners();
  }

  ngOnDestroy() {
    this.removeEventListeners();
  }

  private setupEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.addEventListener('delete', this.deleteHandler);
    }
  }

  private removeEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.removeEventListener('delete', this.deleteHandler);
    }
  }

  private getNativeElement() {
    // For standalone components with template, get the host element itself
    // since we're using selector: 'ytz-chip'
    if (typeof window !== 'undefined') {
      return document.querySelector('ytz-chip');
    }
    return null;
  }
}
