// packages/svelte/src/MenuItem.svelte
<script lang="ts">
	import '@grimoire/yetzirah-core'
	import { onMount } from 'svelte'

	/**
	 * Svelte wrapper for ytz-menuitem Web Component.
	 * Individual menu item with select event.
	 *
	 * @component
	 * @example
	 * ```svelte
	 * <MenuItem on:select={handleEdit}>Edit</MenuItem>
	 * ```
	 *
	 * @example
	 * ```svelte
	 * <MenuItem value="delete" disabled on:select={handleAction}>Delete</MenuItem>
	 * ```
	 */

	let element: HTMLElement & { disabled?: boolean; value?: string }

	/** Disabled state */
	export let disabled = false

	/** Optional value for select event */
	export let value: string | undefined = undefined

	/**
	 * Handle select events from the web component
	 * @private
	 */
	function handleSelect(event: CustomEvent<{ value: string }>) {
		// Event is dispatched by the web component
		// Just forward it through Svelte's event system
	}

	/**
	 * Sync disabled state to web component
	 * @private
	 */
	$: if (element) {
		element.disabled = disabled
	}

	/**
	 * Sync value to web component
	 * @private
	 */
	$: if (element && value !== undefined) {
		element.value = value
	}

	onMount(() => {
		if (element) {
			element.addEventListener('select', handleSelect)

			return () => {
				element.removeEventListener('select', handleSelect)
			}
		}
	})
</script>

<ytz-menuitem
	bind:this={element}
	class={$$restProps.class || ''}
	disabled={disabled || undefined}
	value={value}
	on:select
	{...$$restProps}
>
	<slot />
</ytz-menuitem>

<style>
	:global(ytz-menuitem) {
		display: block;
	}
</style>

// packages/angular/src/lib/menu-item.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnDestroy
} from '@angular/core';
import '@grimoire/yetzirah-core';

/**
 * Angular wrapper for ytz-menuitem Web Component.
 * Individual menu item within a ytz-menu.
 *
 * @example
 * <ytz-menuitem value="edit">Edit</ytz-menuitem>
 *
 * @example
 * <ytz-menuitem [disabled]="true">Disabled Action</ytz-menuitem>
 *
 * @example
 * <ytz-menuitem (select)="onSelect($event)">Delete</ytz-menuitem>
 */
@Component({
  selector: 'ytz-menuitem',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <ng-content></ng-content>
  `,
  styles: []
})
export class MenuItemComponent implements AfterViewInit, OnDestroy {
  /**
   * Optional value for the menu item
   */
  @Input() value?: string;

  /**
   * Disable menu item interactions
   */
  @Input() disabled: boolean = false;

  /**
   * Emitted when the menu item is selected
   */
  @Output() select = new EventEmitter<CustomEvent>();

  @ViewChild('menuItemElement', { read: ElementRef }) menuItemElement!: ElementRef;

  private selectHandler = (e: Event) => {
    this.select.emit(e as CustomEvent);
  };

  ngAfterViewInit() {
    this.setupEventListeners();
  }

  ngOnDestroy() {
    this.removeEventListeners();
  }

  private setupEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.addEventListener('select', this.selectHandler);
    }
  }

  private removeEventListeners() {
    const el = this.getNativeElement();
    if (el) {
      el.removeEventListener('select', this.selectHandler);
    }
  }

  private getNativeElement() {
    // For standalone components with template, get the host element itself
    // since we're using selector: 'ytz-menuitem'
    if (typeof window !== 'undefined') {
      return document.querySelector('ytz-menuitem');
    }
    return null;
  }
}
